package com.tyr.builders;

import java.util.ArrayList;
import java.util.List;

import net.minecraft.block.Block;
import net.minecraft.block.BlockSlab;
import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.item.Item;
import net.minecraft.item.ItemBlock;
import net.minecraft.item.ItemSlab;
import net.minecraftforge.client.event.ModelRegistryEvent;
import net.minecraftforge.client.model.ModelLoader;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.registry.ForgeRegistries;
import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraftforge.fml.common.registry.GameRegistry.ObjectHolder;


@ObjectHolder(TyrBuilders.MODID)
public class TyrBuildersBlocks 
{
	//RESOURCES
    public static Block sugar_cube = new BlockSugarCube("sugar_cube");
    public static Block charcoal_block = new BlockCharcoalBlock("charcoal_block");
    public static Block sugar_cane_block = new BlockSugarCaneBlock("sugar_cane_block");
    public static Block sugar_cane_block_dry = new BlockSugarCaneBlock("sugar_cane_block_dry");
    public static Block wrought_iron_block = new BlockWroughtIronBlock("wrought_iron_block");
    public static Block beehive = new BlockBeehive("beehive");
    public static Block jar_honey = new BlockJarHoney("jar_honey");
    public static Block torch_tiki = new BlockTorchTiki("torch_tiki");
    public static Block torch_tiki_pole = new BlockTorchTikiPole("torch_tiki_pole");
    public static Block straw = new BlockStraw("straw");
    public static Block straw_stairs = new BlockStrawStairs("straw_stairs");
    public static BlockSlab straw_slab = new BlockStrawSlabHalf("straw_slab");
    public static BlockSlab straw_slab_double = new BlockStrawSlabDouble("straw_slab_double");
    public static Block straw_clean = new BlockStraw("straw_clean");
    public static Block straw_clean_stairs = new BlockStrawStairs("straw_clean_stairs");
    public static BlockSlab straw_clean_slab = new BlockStrawSlabHalf("straw_clean_slab");
    public static BlockSlab straw_clean_slab_double = new BlockStrawSlabDouble("straw_clean_slab_double");
    public static Block farmland_enriched = new BlockFarmlandEnriched("farmland_enriched");
    //TEMPERED GLASS
    public static Block glass_tempered = new BlockGlassTempered("glass_tempered");
    public static Block glass_tempered_white = new BlockGlassTempered("glass_tempered_white");  
    public static Block glass_tempered_orange = new BlockGlassTempered("glass_tempered_orange");
    public static Block glass_tempered_magenta = new BlockGlassTempered("glass_tempered_magenta");
    public static Block glass_tempered_light_blue = new BlockGlassTempered("glass_tempered_light_blue");
    public static Block glass_tempered_yellow = new BlockGlassTempered("glass_tempered_yellow");
    public static Block glass_tempered_lime = new BlockGlassTempered("glass_tempered_lime");
    public static Block glass_tempered_pink = new BlockGlassTempered("glass_tempered_pink");
    public static Block glass_tempered_grey = new BlockGlassTempered("glass_tempered_grey"); 
    public static Block glass_tempered_light_grey = new BlockGlassTempered("glass_tempered_light_grey");
    public static Block glass_tempered_cyan = new BlockGlassTempered("glass_tempered_cyan");
    public static Block glass_tempered_purple = new BlockGlassTempered("glass_tempered_purple");
    public static Block glass_tempered_blue = new BlockGlassTempered("glass_tempered_blue");
    public static Block glass_tempered_brown = new BlockGlassTempered("glass_tempered_brown");
    public static Block glass_tempered_green = new BlockGlassTempered("glass_tempered_green");
    public static Block glass_tempered_red = new BlockGlassTempered("glass_tempered_red");
    public static Block glass_tempered_black = new BlockGlassTempered("glass_tempered_black");
    //TEMPERED GLASS STAIRS
    public static Block glass_tempered_stairs = new BlockGlassTemperedStairs("glass_tempered_stairs");
    public static Block glass_tempered_white_stairs = new BlockGlassTemperedStairs("glass_tempered_white_stairs");
    public static Block glass_tempered_orange_stairs = new BlockGlassTemperedStairs("glass_tempered_orange_stairs");
    public static Block glass_tempered_magenta_stairs = new BlockGlassTemperedStairs("glass_tempered_magenta_stairs");
    public static Block glass_tempered_light_blue_stairs = new BlockGlassTemperedStairs("glass_tempered_light_blue_stairs");
    public static Block glass_tempered_yellow_stairs = new BlockGlassTemperedStairs("glass_tempered_yellow_stairs");
    public static Block glass_tempered_lime_stairs = new BlockGlassTemperedStairs("glass_tempered_lime_stairs");
    public static Block glass_tempered_pink_stairs = new BlockGlassTemperedStairs("glass_tempered_pink_stairs");
    public static Block glass_tempered_grey_stairs = new BlockGlassTemperedStairs("glass_tempered_grey_stairs");
    public static Block glass_tempered_light_grey_stairs = new BlockGlassTemperedStairs("glass_tempered_light_grey_stairs"); 
    public static Block glass_tempered_cyan_stairs = new BlockGlassTemperedStairs("glass_tempered_cyan_stairs");
    public static Block glass_tempered_purple_stairs = new BlockGlassTemperedStairs("glass_tempered_purple_stairs"); 
    public static Block glass_tempered_blue_stairs = new BlockGlassTemperedStairs("glass_tempered_blue_stairs");
    public static Block glass_tempered_brown_stairs = new BlockGlassTemperedStairs("glass_tempered_brown_stairs");
    public static Block glass_tempered_green_stairs = new BlockGlassTemperedStairs("glass_tempered_green_stairs"); 
    public static Block glass_tempered_red_stairs = new BlockGlassTemperedStairs("glass_tempered_red_stairs");
    public static Block glass_tempered_black_stairs = new BlockGlassTemperedStairs("glass_tempered_black_stairs");
    //TEMPERED GLASS SLAB
    public static BlockSlab glass_tempered_slab = new BlockGlassTemperedSlabHalf("glass_tempered_slab");
    public static BlockSlab glass_tempered_slab_double = new BlockGlassTemperedSlabDouble("glass_tempered_slab_double");
    public static BlockSlab glass_tempered_white_slab = new BlockGlassTemperedSlabHalf("glass_tempered_white_slab");
    public static BlockSlab glass_tempered_white_slab_double = new BlockGlassTemperedSlabDouble("glass_tempered_white_slab_double");  
    public static BlockSlab glass_tempered_orange_slab = new BlockGlassTemperedSlabHalf("glass_tempered_orange_slab");
    public static BlockSlab glass_tempered_orange_slab_double = new BlockGlassTemperedSlabDouble("glass_tempered_orange_slab_double");  
    public static BlockSlab glass_tempered_magenta_slab = new BlockGlassTemperedSlabHalf("glass_tempered_magenta_slab");
    public static BlockSlab glass_tempered_magenta_slab_double = new BlockGlassTemperedSlabDouble("glass_tempered_magenta_slab_double");  
    public static BlockSlab glass_tempered_light_blue_slab = new BlockGlassTemperedSlabHalf("glass_tempered_light_blue_slab");
    public static BlockSlab glass_tempered_light_blue_slab_double = new BlockGlassTemperedSlabDouble("glass_tempered_light_blue_slab_double");  
    public static BlockSlab glass_tempered_yellow_slab = new BlockGlassTemperedSlabHalf("glass_tempered_yellow_slab");
    public static BlockSlab glass_tempered_yellow_slab_double = new BlockGlassTemperedSlabDouble("glass_tempered_yellow_slab_double"); 
    public static BlockSlab glass_tempered_lime_slab = new BlockGlassTemperedSlabHalf("glass_tempered_lime_slab");
    public static BlockSlab glass_tempered_lime_slab_double = new BlockGlassTemperedSlabDouble("glass_tempered_lime_slab_double");  
    public static BlockSlab glass_tempered_pink_slab = new BlockGlassTemperedSlabHalf("glass_tempered_pink_slab");
    public static BlockSlab glass_tempered_pink_slab_double = new BlockGlassTemperedSlabDouble("glass_tempered_pink_slab_double");  
    public static BlockSlab glass_tempered_grey_slab = new BlockGlassTemperedSlabHalf("glass_tempered_grey_slab");
    public static BlockSlab glass_tempered_grey_slab_double = new BlockGlassTemperedSlabDouble("glass_tempered_grey_slab_double"); 
    public static BlockSlab glass_tempered_light_grey_slab = new BlockGlassTemperedSlabHalf("glass_tempered_light_grey_slab");
    public static BlockSlab glass_tempered_light_grey_slab_double = new BlockGlassTemperedSlabDouble("glass_tempered_light_grey_slab_double"); 
    public static BlockSlab glass_tempered_cyan_slab = new BlockGlassTemperedSlabHalf("glass_tempered_cyan_slab");
    public static BlockSlab glass_tempered_cyan_slab_double = new BlockGlassTemperedSlabDouble("glass_tempered_cyan_slab_double"); 
    public static BlockSlab glass_tempered_purple_slab = new BlockGlassTemperedSlabHalf("glass_tempered_purple_slab");
    public static BlockSlab glass_tempered_purple_slab_double = new BlockGlassTemperedSlabDouble("glass_tempered_purple_slab_double"); 
    public static BlockSlab glass_tempered_blue_slab = new BlockGlassTemperedSlabHalf("glass_tempered_blue_slab");
    public static BlockSlab glass_tempered_blue_slab_double = new BlockGlassTemperedSlabDouble("glass_tempered_blue_slab_double"); 
    public static BlockSlab glass_tempered_brown_slab = new BlockGlassTemperedSlabHalf("glass_tempered_brown_slab");
    public static BlockSlab glass_tempered_brown_slab_double = new BlockGlassTemperedSlabDouble("glass_tempered_brown_slab_double");
    public static BlockSlab glass_tempered_green_slab = new BlockGlassTemperedSlabHalf("glass_tempered_green_slab");
    public static BlockSlab glass_tempered_green_slab_double = new BlockGlassTemperedSlabDouble("glass_tempered_green_slab_double"); 
    public static BlockSlab glass_tempered_red_slab = new BlockGlassTemperedSlabHalf("glass_tempered_red_slab");
    public static BlockSlab glass_tempered_red_slab_double = new BlockGlassTemperedSlabDouble("glass_tempered_red_slab_double"); 
    public static BlockSlab glass_tempered_black_slab = new BlockGlassTemperedSlabHalf("glass_tempered_black_slab");
    public static BlockSlab glass_tempered_black_slab_double = new BlockGlassTemperedSlabDouble("glass_tempered_black_slab_double"); 
    //TEMPERED GLASS PANE
    public static Block glass_tempered_pane = new BlockGlassTemperedPane("glass_tempered_pane");
    public static Block glass_tempered_pane_white = new BlockGlassTemperedPane("glass_tempered_pane_white");
    public static Block glass_tempered_pane_orange = new BlockGlassTemperedPane("glass_tempered_pane_orange");
    public static Block glass_tempered_pane_magenta = new BlockGlassTemperedPane("glass_tempered_pane_magenta");
    public static Block glass_tempered_pane_light_blue = new BlockGlassTemperedPane("glass_tempered_pane_light_blue"); 
    public static Block glass_tempered_pane_yellow = new BlockGlassTemperedPane("glass_tempered_pane_yellow");
    public static Block glass_tempered_pane_lime = new BlockGlassTemperedPane("glass_tempered_pane_lime");
    public static Block glass_tempered_pane_pink = new BlockGlassTemperedPane("glass_tempered_pane_pink");
    public static Block glass_tempered_pane_grey = new BlockGlassTemperedPane("glass_tempered_pane_grey");
    public static Block glass_tempered_pane_light_grey = new BlockGlassTemperedPane("glass_tempered_pane_light_grey"); 
    public static Block glass_tempered_pane_cyan = new BlockGlassTemperedPane("glass_tempered_pane_cyan");
    public static Block glass_tempered_pane_purple = new BlockGlassTemperedPane("glass_tempered_pane_purple");
    public static Block glass_tempered_pane_blue = new BlockGlassTemperedPane("glass_tempered_pane_blue");
    public static Block glass_tempered_pane_brown = new BlockGlassTemperedPane("glass_tempered_pane_brown");
    public static Block glass_tempered_pane_green = new BlockGlassTemperedPane("glass_tempered_pane_green");
    public static Block glass_tempered_pane_red = new BlockGlassTemperedPane("glass_tempered_pane_red");
    public static Block glass_tempered_pane_black = new BlockGlassTemperedPane("glass_tempered_pane_black");
    //STONE and DIRT STAIRS
    public static Block stone_stairs = new BlockStoneStairs("stone_stairs");
    public static Block stone_andesite_stairs = new BlockStoneStairs("stone_andesite_stairs");
    public static Block stone_diorite_stairs = new BlockStoneStairs("stone_diorite_stairs");
    public static Block stone_granite_stairs = new BlockStoneStairs("stone_granite_stairs");
    public static Block stone_andesite_smooth_stairs = new BlockStoneStairs("stone_andesite_smooth_stairs");
    public static Block stone_diorite_smooth_stairs = new BlockStoneStairs("stone_diorite_smooth_stairs");
    public static Block stone_granite_smooth_stairs = new BlockStoneStairs("stone_granite_smooth_stairs");
    //TERACOTA STAIRS
    public static Block hardened_clay_stairs = new BlockHardenedClayStairs("hardened_clay_stairs");
    public static Block hardened_clay_stained_white_stairs = new BlockHardenedClayStairs("hardened_clay_stained_white_stairs"); 
    public static Block hardened_clay_stained_orange_stairs = new BlockHardenedClayStairs("hardened_clay_stained_orange_stairs");
    public static Block hardened_clay_stained_magenta_stairs = new BlockHardenedClayStairs("hardened_clay_stained_magenta_stairs");
    public static Block hardened_clay_stained_light_blue_stairs = new BlockHardenedClayStairs("hardened_clay_stained_light_blue_stairs");
    public static Block hardened_clay_stained_yellow_stairs = new BlockHardenedClayStairs("hardened_clay_stained_yellow_stairs");
    public static Block hardened_clay_stained_lime_stairs = new BlockHardenedClayStairs("hardened_clay_stained_lime_stairs");
    public static Block hardened_clay_stained_pink_stairs = new BlockHardenedClayStairs("hardened_clay_stained_pink_stairs");
    public static Block hardened_clay_stained_grey_stairs = new BlockHardenedClayStairs("hardened_clay_stained_grey_stairs");
    public static Block hardened_clay_stained_light_grey_stairs = new BlockHardenedClayStairs("hardened_clay_stained_light_grey_stairs");
    public static Block hardened_clay_stained_cyan_stairs = new BlockHardenedClayStairs("hardened_clay_stained_cyan_stairs");
    public static Block hardened_clay_stained_purple_stairs = new BlockHardenedClayStairs("hardened_clay_stained_purple_stairs");
    public static Block hardened_clay_stained_blue_stairs = new BlockHardenedClayStairs("hardened_clay_stained_blue_stairs");
    public static Block hardened_clay_stained_brown_stairs = new BlockHardenedClayStairs("hardened_clay_stained_brown_stairs");
    public static Block hardened_clay_stained_green_stairs = new BlockHardenedClayStairs("hardened_clay_stained_green_stairs");
    public static Block hardened_clay_stained_red_stairs = new BlockHardenedClayStairs("hardened_clay_stained_red_stairs");
    public static Block hardened_clay_stained_black_stairs = new BlockHardenedClayStairs("hardened_clay_stained_black_stairs");
    //STONEBRICKS
    public static Block stonebrick_andesite = new BlockStoneBrick("stonebrick_andesite");
    public static Block stonebrick_diorite = new BlockStoneBrick("stonebrick_diorite");
    public static Block stonebrick_granite = new BlockStoneBrick("stonebrick_granite");
    //PILLARS
    public static Block stonebrick_pillar = new BlockStonePillar("stonebrick_pillar");
    public static Block stone_andesite_pillar = new BlockStonePillar("stone_andesite_pillar");
    public static Block stone_diorite_pillar = new BlockStonePillar("stone_diorite_pillar");
    public static Block stone_granite_pillar = new BlockStonePillar("stone_granite_pillar");
    //WALLS
    public static Block sandstone_wall = new BlockSandstoneWall("sandstone_wall");
    public static Block red_sandstone_wall = new BlockSandstoneWall("red_sandstone_wall");
    public static Block stone_andesite_wall = new BlockStoneWall("stone_andesite_wall");
    public static Block stone_diorite_wall = new BlockStoneWall("stone_diorite_wall");
    public static Block stone_granite_wall = new BlockStoneWall("stone_granite_wall");
    //PEDESTALS
    public static Block stone_pedestal = new BlockStonePedestal("stone_pedestal");
    public static Block stone_andesite_pedestal = new BlockStonePedestal("stone_andesite_pedestal");
    public static Block stone_diorite_pedestal = new BlockStonePedestal("stone_diorite_pedestal");
    public static Block stone_granite_pedestal = new BlockStonePedestal("stone_granite_pedestal");
    public static Block sandstone_pedestal = new BlockStonePedestal("sandstone_pedestal");
    public static Block red_sandstone_pedestal = new BlockStonePedestal("red_sandstone_pedestal");
    public static Block quartz_pedestal = new BlockStonePedestal("quartz_pedestal");
    //TERACOTA SLAB HALF
    public static BlockSlab hardened_clay_stained_slab = new BlockHardenedClaySlabHalf("hardened_clay_stained_slab");
    public static BlockSlab hardened_clay_stained_slab_double = new BlockHardenedClaySlabDouble("hardened_clay_stained_slab_double");
    public static BlockSlab hardened_clay_stained_white_slab = new BlockHardenedClaySlabHalf("hardened_clay_stained_white_slab");
    public static BlockSlab hardened_clay_stained_white_slab_double = new BlockHardenedClaySlabDouble("hardened_clay_stained_white_slab_double");  
    public static BlockSlab hardened_clay_stained_orange_slab = new BlockHardenedClaySlabHalf("hardened_clay_stained_orange_slab");
    public static BlockSlab hardened_clay_stained_orange_slab_double = new BlockHardenedClaySlabDouble("hardened_clay_stained_orange_slab_double");  
    public static BlockSlab hardened_clay_stained_magenta_slab = new BlockHardenedClaySlabHalf("hardened_clay_stained_magenta_slab");
    public static BlockSlab hardened_clay_stained_magenta_slab_double = new BlockHardenedClaySlabDouble("hardened_clay_stained_magenta_slab_double");  
    public static BlockSlab hardened_clay_stained_light_blue_slab = new BlockHardenedClaySlabHalf("hardened_clay_stained_light_blue_slab");
    public static BlockSlab hardened_clay_stained_light_blue_slab_double = new BlockHardenedClaySlabDouble("hardened_clay_stained_light_blue_slab_double");  
    public static BlockSlab hardened_clay_stained_yellow_slab = new BlockHardenedClaySlabHalf("hardened_clay_stained_yellow_slab");
    public static BlockSlab hardened_clay_stained_yellow_slab_double = new BlockHardenedClaySlabDouble("hardened_clay_stained_yellow_slab_double"); 
    public static BlockSlab hardened_clay_stained_lime_slab = new BlockHardenedClaySlabHalf("hardened_clay_stained_lime_slab");
    public static BlockSlab hardened_clay_stained_lime_slab_double = new BlockHardenedClaySlabDouble("hardened_clay_stained_lime_slab_double");  
    public static BlockSlab hardened_clay_stained_pink_slab = new BlockHardenedClaySlabHalf("hardened_clay_stained_pink_slab");
    public static BlockSlab hardened_clay_stained_pink_slab_double = new BlockHardenedClaySlabDouble("hardened_clay_stained_pink_slab_double");  
    public static BlockSlab hardened_clay_stained_grey_slab = new BlockHardenedClaySlabHalf("hardened_clay_stained_grey_slab");
    public static BlockSlab hardened_clay_stained_grey_slab_double = new BlockHardenedClaySlabDouble("hardened_clay_stained_grey_slab_double"); 
    public static BlockSlab hardened_clay_stained_light_grey_slab = new BlockHardenedClaySlabHalf("hardened_clay_stained_light_grey_slab");
    public static BlockSlab hardened_clay_stained_light_grey_slab_double = new BlockHardenedClaySlabDouble("hardened_clay_stained_light_grey_slab_double"); 
    public static BlockSlab hardened_clay_stained_cyan_slab = new BlockHardenedClaySlabHalf("hardened_clay_stained_cyan_slab");
    public static BlockSlab hardened_clay_stained_cyan_slab_double = new BlockHardenedClaySlabDouble("hardened_clay_stained_cyan_slab_double"); 
    public static BlockSlab hardened_clay_stained_purple_slab = new BlockHardenedClaySlabHalf("hardened_clay_stained_purple_slab");
    public static BlockSlab hardened_clay_stained_purple_slab_double = new BlockHardenedClaySlabDouble("hardened_clay_stained_purple_slab_double"); 
    public static BlockSlab hardened_clay_stained_blue_slab = new BlockHardenedClaySlabHalf("hardened_clay_stained_blue_slab");
    public static BlockSlab hardened_clay_stained_blue_slab_double = new BlockHardenedClaySlabDouble("hardened_clay_stained_blue_slab_double"); 
    public static BlockSlab hardened_clay_stained_brown_slab = new BlockHardenedClaySlabHalf("hardened_clay_stained_brown_slab");
    public static BlockSlab hardened_clay_stained_brown_slab_double = new BlockHardenedClaySlabDouble("hardened_clay_stained_brown_slab_double");
    public static BlockSlab hardened_clay_stained_green_slab = new BlockHardenedClaySlabHalf("hardened_clay_stained_green_slab");
    public static BlockSlab hardened_clay_stained_green_slab_double = new BlockHardenedClaySlabDouble("hardened_clay_stained_green_slab_double"); 
    public static BlockSlab hardened_clay_stained_red_slab = new BlockHardenedClaySlabHalf("hardened_clay_stained_red_slab");
    public static BlockSlab hardened_clay_stained_red_slab_double = new BlockHardenedClaySlabDouble("hardened_clay_stained_red_slab_double"); 
    public static BlockSlab hardened_clay_stained_black_slab = new BlockHardenedClaySlabHalf("hardened_clay_stained_black_slab");
    public static BlockSlab hardened_clay_stained_black_slab_double = new BlockHardenedClaySlabDouble("hardened_clay_stained_black_slab_double");
    //WOOL SLAB HALF
    public static BlockSlab wool_white_slab = new BlockWoolSlabHalf("wool_white_slab");
    public static BlockSlab wool_white_slab_double = new BlockWoolSlabDouble("wool_white_slab_double");  
    public static BlockSlab wool_orange_slab = new BlockWoolSlabHalf("wool_orange_slab");
    public static BlockSlab wool_orange_slab_double = new BlockWoolSlabDouble("wool_orange_slab_double");  
    public static BlockSlab wool_magenta_slab = new BlockWoolSlabHalf("wool_magenta_slab");
    public static BlockSlab wool_magenta_slab_double = new BlockWoolSlabDouble("wool_magenta_slab_double");  
    public static BlockSlab wool_light_blue_slab = new BlockWoolSlabHalf("wool_light_blue_slab");
    public static BlockSlab wool_light_blue_slab_double = new BlockWoolSlabDouble("wool_light_blue_slab_double");  
    public static BlockSlab wool_yellow_slab = new BlockWoolSlabHalf("wool_yellow_slab");
    public static BlockSlab wool_yellow_slab_double = new BlockWoolSlabDouble("wool_yellow_slab_double"); 
    public static BlockSlab wool_lime_slab = new BlockWoolSlabHalf("wool_lime_slab");
    public static BlockSlab wool_lime_slab_double = new BlockWoolSlabDouble("wool_lime_slab_double");  
    public static BlockSlab wool_pink_slab = new BlockWoolSlabHalf("wool_pink_slab");
    public static BlockSlab wool_pink_slab_double = new BlockWoolSlabDouble("wool_pink_slab_double");  
    public static BlockSlab wool_grey_slab = new BlockWoolSlabHalf("wool_grey_slab");
    public static BlockSlab wool_grey_slab_double = new BlockWoolSlabDouble("wool_grey_slab_double"); 
    public static BlockSlab wool_light_grey_slab = new BlockWoolSlabHalf("wool_light_grey_slab");
    public static BlockSlab wool_light_grey_slab_double = new BlockWoolSlabDouble("wool_light_grey_slab_double"); 
    public static BlockSlab wool_cyan_slab = new BlockWoolSlabHalf("wool_cyan_slab");
    public static BlockSlab wool_cyan_slab_double = new BlockWoolSlabDouble("wool_cyan_slab_double"); 
    public static BlockSlab wool_purple_slab = new BlockWoolSlabHalf("wool_purple_slab");
    public static BlockSlab wool_purple_slab_double = new BlockWoolSlabDouble("wool_purple_slab_double"); 
    public static BlockSlab wool_blue_slab = new BlockWoolSlabHalf("wool_blue_slab");
    public static BlockSlab wool_blue_slab_double = new BlockWoolSlabDouble("wool_blue_slab_double"); 
    public static BlockSlab wool_brown_slab = new BlockWoolSlabHalf("wool_brown_slab");
    public static BlockSlab wool_brown_slab_double = new BlockWoolSlabDouble("wool_brown_slab_double");
    public static BlockSlab wool_green_slab = new BlockWoolSlabHalf("wool_green_slab");
    public static BlockSlab wool_green_slab_double = new BlockWoolSlabDouble("wool_green_slab_double"); 
    public static BlockSlab wool_red_slab = new BlockWoolSlabHalf("wool_red_slab");
    public static BlockSlab wool_red_slab_double = new BlockWoolSlabDouble("wool_red_slab_double"); 
    public static BlockSlab wool_black_slab = new BlockWoolSlabHalf("wool_black_slab");
    public static BlockSlab wool_black_slab_double = new BlockWoolSlabDouble("wool_black_slab_double");
    //STRINGER TRIANGLES
//	public static Block stringer_spacer = new BlockStringerSpacer("stringer_spacer");
//	public static Block stringer_white_triangle = new BlockStringerTriangle("stringer_white_triangle");
//	public static Block stringer_orange_triangle = new BlockStringerTriangle("stringer_orange_triangle");  	
//	public static Block stringer_magenta_triangle = new BlockStringerTriangle("stringer_magenta_triangle");	
//	public static Block stringer_light_blue_triangle = new BlockStringerTriangle("stringer_light_blue_triangle");  	
//	public static Block stringer_yellow_triangle = new BlockStringerTriangle("stringer_yellow_triangle");  	
//	public static Block stringer_lime_triangle = new BlockStringerTriangle("stringer_lime_triangle");  	
//	public static Block stringer_pink_triangle = new BlockStringerTriangle("stringer_pink_triangle");  	
//	public static Block stringer_grey_triangle = new BlockStringerTriangle("stringer_grey_triangle");  	
//	public static Block stringer_light_grey_triangle = new BlockStringerTriangle("stringer_light_grey_triangle"); 	
//	public static Block stringer_cyan_triangle = new BlockStringerTriangle("stringer_cyan_triangle");	
//	public static Block stringer_purple_triangle = new BlockStringerTriangle("stringer_purple_triangle");    	
//	public static Block stringer_blue_triangle = new BlockStringerTriangle("stringer_blue_triangle");   	
//	public static Block stringer_brown_triangle = new BlockStringerTriangle("stringer_brown_triangle");	
//	public static Block stringer_green_triangle = new BlockStringerTriangle("stringer_green_triangle"); 	
//	public static Block stringer_red_triangle = new BlockStringerTriangle("stringer_red_triangle");  	
//	public static Block stringer_black_triangle = new BlockStringerTriangle("stringer_black_triangle");
//	//STRINGER DOVETAILS
//	public static Block stringer_white_dovetail = new BlockStringerDovetail("stringer_white_dovetail");
//	public static Block stringer_orange_dovetail = new BlockStringerDovetail("stringer_orange_dovetail");  	
//	public static Block stringer_magenta_dovetail = new BlockStringerDovetail("stringer_magenta_dovetail");	
//	public static Block stringer_light_blue_dovetail = new BlockStringerDovetail("stringer_light_blue_dovetail");  	
//	public static Block stringer_yellow_dovetail = new BlockStringerDovetail("stringer_yellow_dovetail");  	
//	public static Block stringer_lime_dovetail = new BlockStringerDovetail("stringer_lime_dovetail");  	
//	public static Block stringer_pink_dovetail = new BlockStringerDovetail("stringer_pink_dovetail");  	
//	public static Block stringer_grey_dovetail = new BlockStringerDovetail("stringer_grey_dovetail");  	
//	public static Block stringer_light_grey_dovetail = new BlockStringerDovetail("stringer_light_grey_dovetail"); 	
//	public static Block stringer_cyan_dovetail = new BlockStringerDovetail("stringer_cyan_dovetail");	
//	public static Block stringer_purple_dovetail = new BlockStringerDovetail("stringer_purple_dovetail");    	
//	public static Block stringer_blue_dovetail = new BlockStringerDovetail("stringer_blue_dovetail");   	
//	public static Block stringer_brown_dovetail = new BlockStringerDovetail("stringer_brown_dovetail");	
//	public static Block stringer_green_dovetail = new BlockStringerDovetail("stringer_green_dovetail"); 	
//	public static Block stringer_red_dovetail = new BlockStringerDovetail("stringer_red_dovetail");  	
//	public static Block stringer_black_dovetail = new BlockStringerDovetail("stringer_black_dovetail");
    //STONE SLAB HALF
	public static BlockSlab mossy_cobblestone_slab = new BlockStoneSlabHalf("mossy_cobblestone_slab");
    public static BlockSlab mossy_cobblestone_slab_double = new BlockStoneSlabDouble("mossy_cobblestone_slab_double");  
	public static BlockSlab stone_andesite_slab = new BlockStoneSlabHalf("stone_andesite_slab");
    public static BlockSlab stone_andesite_slab_double = new BlockStoneSlabDouble("stone_andesite_slab_double");  
	public static BlockSlab stone_diorite_slab = new BlockStoneSlabHalf("stone_diorite_slab");
    public static BlockSlab stone_diorite_slab_double = new BlockStoneSlabDouble("stone_diorite_slab_double");  
	public static BlockSlab stone_granite_slab = new BlockStoneSlabHalf("stone_granite_slab");
    public static BlockSlab stone_granite_slab_double = new BlockStoneSlabDouble("stone_granite_slab_double");  
	public static BlockSlab stone_andesite_smooth_slab = new BlockStoneSlabHalf("stone_andesite_smooth_slab");
    public static BlockSlab stone_andesite_smooth_slab_double = new BlockStoneSlabDouble("stone_andesite_smooth_slab_double");  
	public static BlockSlab stone_diorite_smooth_slab = new BlockStoneSlabHalf("stone_diorite_smooth_slab");
    public static BlockSlab stone_diorite_smooth_slab_double = new BlockStoneSlabDouble("stone_diorite_smooth_slab_double");  
	public static BlockSlab stone_granite_smooth_slab = new BlockStoneSlabHalf("stone_granite_smooth_slab");
    public static BlockSlab stone_granite_smooth_slab_double = new BlockStoneSlabDouble("stone_granite_smooth_slab_double");  
    //ARROWSLIT WALLS
	public static Block stone_smooth_arrowslit_wall = new BlockStoneArrowslitWall("stone_smooth_arrowslit_wall");
	public static Block stone_andesite_smooth_arrowslit_wall = new BlockStoneArrowslitWall("stone_andesite_smooth_arrowslit_wall");
	public static Block stone_diorite_smooth_arrowslit_wall = new BlockStoneArrowslitWall("stone_diorite_smooth_arrowslit_wall");
	public static Block stone_granite_smooth_arrowslit_wall = new BlockStoneArrowslitWall("stone_granite_smooth_arrowslit_wall");
	public static Block sandstone_arrowslit_wall = new BlockSandstoneArrowslitWall("sandstone_arrowslit_wall");
	public static Block red_sandstone_arrowslit_wall = new BlockSandstoneArrowslitWall("red_sandstone_arrowslit_wall");
    //PAPER WALLS
    public static Block paper_wall_oak = new BlockPaperWall("paper_wall_oak");
    public static Block paper_wall_spruce = new BlockPaperWall("paper_wall_spruce");
    public static Block paper_wall_birch = new BlockPaperWall("paper_wall_birch");
    public static Block paper_wall_jungle = new BlockPaperWall("paper_wall_jungle");
    public static Block paper_wall_acacia = new BlockPaperWall("paper_wall_acacia");
    public static Block paper_wall_dark_oak = new BlockPaperWall("paper_wall_dark_oak");
    //LOG SHARP
    public static Block log_sharp_oak = new BlockLogSharp("log_sharp_oak");
    public static Block log_sharp_spruce = new BlockLogSharp("log_sharp_spruce");
    public static Block log_sharp_birch = new BlockLogSharp("log_sharp_birch");
    public static Block log_sharp_jungle = new BlockLogSharp("log_sharp_jungle");
    public static Block log_sharp_acacia = new BlockLogSharp("log_sharp_acacia");
    public static Block log_sharp_dark_oak = new BlockLogSharp("log_sharp_dark_oak");
    //LOG DULL
    public static Block log_dull_oak = new BlockLogDull("log_dull_oak");
    public static Block log_dull_spruce = new BlockLogDull("log_dull_spruce");
    public static Block log_dull_birch = new BlockLogDull("log_dull_birch");
    public static Block log_dull_jungle = new BlockLogDull("log_dull_jungle");
    public static Block log_dull_acacia = new BlockLogDull("log_dull_acacia");
    public static Block log_dull_dark_oak = new BlockLogDull("log_dull_dark_oak");
    //CABINET ANDESITE
    public static Block cabinet_oak_andesite = new BlockCabinet("cabinet_oak_andesite");
    public static Block cabinet_spruce_andesite = new BlockCabinet("cabinet_spruce_andesite");
    public static Block cabinet_birch_andesite = new BlockCabinet("cabinet_birch_andesite");
    public static Block cabinet_jungle_andesite = new BlockCabinet("cabinet_jungle_andesite");
    public static Block cabinet_acacia_andesite = new BlockCabinet("cabinet_acacia_andesite");
    public static Block cabinet_dark_oak_andesite = new BlockCabinet("cabinet_dark_oak_andesite");
    //CABINET DIORITE
    public static Block cabinet_oak_diorite = new BlockCabinet("cabinet_oak_diorite");
    public static Block cabinet_spruce_diorite = new BlockCabinet("cabinet_spruce_diorite");
    public static Block cabinet_birch_diorite = new BlockCabinet("cabinet_birch_diorite");
    public static Block cabinet_jungle_diorite = new BlockCabinet("cabinet_jungle_diorite");
    public static Block cabinet_acacia_diorite = new BlockCabinet("cabinet_acacia_diorite");
    public static Block cabinet_dark_oak_diorite = new BlockCabinet("cabinet_dark_oak_diorite");
    //CABINET GRANITE
    public static Block cabinet_oak_granite = new BlockCabinet("cabinet_oak_granite");
    public static Block cabinet_spruce_granite = new BlockCabinet("cabinet_spruce_granite");
    public static Block cabinet_birch_granite = new BlockCabinet("cabinet_birch_granite");
    public static Block cabinet_jungle_granite = new BlockCabinet("cabinet_jungle_granite");
    public static Block cabinet_acacia_granite = new BlockCabinet("cabinet_acacia_granite");
    public static Block cabinet_dark_oak_granite = new BlockCabinet("cabinet_dark_oak_granite");
    //CABINET STONE
    public static Block cabinet_oak_stone = new BlockCabinet("cabinet_oak_stone");
    public static Block cabinet_spruce_stone = new BlockCabinet("cabinet_spruce_stone");
    public static Block cabinet_birch_stone = new BlockCabinet("cabinet_birch_stone");
    public static Block cabinet_jungle_stone = new BlockCabinet("cabinet_jungle_stone");
    public static Block cabinet_acacia_stone = new BlockCabinet("cabinet_acacia_stone");
    public static Block cabinet_dark_oak_stone = new BlockCabinet("cabinet_dark_oak_stone");
    //CABINET DRAWERS ANDESITE
    public static Block cabinet_drawers_oak_andesite = new BlockCabinetDrawers("cabinet_drawers_oak_andesite");
    public static Block cabinet_drawers_spruce_andesite = new BlockCabinetDrawers("cabinet_drawers_spruce_andesite");
    public static Block cabinet_drawers_birch_andesite = new BlockCabinetDrawers("cabinet_drawers_birch_andesite");
    public static Block cabinet_drawers_jungle_andesite = new BlockCabinetDrawers("cabinet_drawers_jungle_andesite");
    public static Block cabinet_drawers_acacia_andesite = new BlockCabinetDrawers("cabinet_drawers_acacia_andesite");
    public static Block cabinet_drawers_dark_oak_andesite = new BlockCabinetDrawers("cabinet_drawers_dark_oak_andesite");
    //CABINET DRAWERS DIORITE
    public static Block cabinet_drawers_oak_diorite = new BlockCabinetDrawers("cabinet_drawers_oak_diorite");
    public static Block cabinet_drawers_spruce_diorite = new BlockCabinetDrawers("cabinet_drawers_spruce_diorite");
    public static Block cabinet_drawers_birch_diorite = new BlockCabinetDrawers("cabinet_drawers_birch_diorite");
    public static Block cabinet_drawers_jungle_diorite = new BlockCabinetDrawers("cabinet_drawers_jungle_diorite");
    public static Block cabinet_drawers_acacia_diorite = new BlockCabinetDrawers("cabinet_drawers_acacia_diorite");
    public static Block cabinet_drawers_dark_oak_diorite = new BlockCabinetDrawers("cabinet_drawers_dark_oak_diorite");
    //CABINET DRAWERS GRANITE
    public static Block cabinet_drawers_oak_granite = new BlockCabinetDrawers("cabinet_drawers_oak_granite");
    public static Block cabinet_drawers_spruce_granite = new BlockCabinetDrawers("cabinet_drawers_spruce_granite");
    public static Block cabinet_drawers_birch_granite = new BlockCabinetDrawers("cabinet_drawers_birch_granite");
    public static Block cabinet_drawers_jungle_granite = new BlockCabinetDrawers("cabinet_drawers_jungle_granite");
    public static Block cabinet_drawers_acacia_granite = new BlockCabinetDrawers("cabinet_drawers_acacia_granite");
    public static Block cabinet_drawers_dark_oak_granite = new BlockCabinetDrawers("cabinet_drawers_dark_oak_granite");
    //CABINET DRAWERS STONE
    public static Block cabinet_drawers_oak_stone = new BlockCabinetDrawers("cabinet_drawers_oak_stone");
    public static Block cabinet_drawers_spruce_stone = new BlockCabinetDrawers("cabinet_drawers_spruce_stone");
    public static Block cabinet_drawers_birch_stone = new BlockCabinetDrawers("cabinet_drawers_birch_stone");
    public static Block cabinet_drawers_jungle_stone = new BlockCabinetDrawers("cabinet_drawers_jungle_stone");
    public static Block cabinet_drawers_acacia_stone = new BlockCabinetDrawers("cabinet_drawers_acacia_stone");
    public static Block cabinet_drawers_dark_oak_stone = new BlockCabinetDrawers("cabinet_drawers_dark_oak_stone");
    //CABINET DOORS
    public static Block cabinet_doors_oak = new BlockCabinetDoors("cabinet_doors_oak");
    public static Block cabinet_doors_spruce = new BlockCabinetDoors("cabinet_doors_spruce");
    public static Block cabinet_doors_birch = new BlockCabinetDoors("cabinet_doors_birch");
    public static Block cabinet_doors_jungle = new BlockCabinetDoors("cabinet_doors_jungle");
    public static Block cabinet_doors_acacia = new BlockCabinetDoors("cabinet_doors_acacia");
    public static Block cabinet_doors_dark_oak = new BlockCabinetDoors("cabinet_doors_dark_oak");
    //CRATE SMALL
    public static Block crate_small_oak = new BlockCrateSmall("crate_small_oak");
    public static Block crate_small_spruce = new BlockCrateSmall("crate_small_spruce");
    public static Block crate_small_birch = new BlockCrateSmall("crate_small_birch");
    public static Block crate_small_jungle = new BlockCrateSmall("crate_small_jungle");
    public static Block crate_small_acacia = new BlockCrateSmall("crate_small_acacia");
    public static Block crate_small_dark_oak = new BlockCrateSmall("crate_small_dark_oak");
    //CRATE
    public static Block crate_oak = new BlockCrate("crate_oak");
    public static Block crate_spruce = new BlockCrate("crate_spruce");
    public static Block crate_birch = new BlockCrate("crate_birch");
    public static Block crate_jungle = new BlockCrate("crate_jungle");
    public static Block crate_acacia = new BlockCrate("crate_acacia");
    public static Block crate_dark_oak = new BlockCrate("crate_dark_oak");
    //BARREL
    public static Block barrel_oak = new BlockBarrel("barrel_oak");
    public static Block barrel_spruce = new BlockBarrel("barrel_spruce");
    public static Block barrel_birch = new BlockBarrel("barrel_birch");
    public static Block barrel_jungle = new BlockBarrel("barrel_jungle");
    public static Block barrel_acacia = new BlockBarrel("barrel_acacia");
    public static Block barrel_dark_oak = new BlockBarrel("barrel_dark_oak");
    //BARREL HALF
    public static Block barrel_cut_oak = new BlockBarrelCut("barrel_cut_oak");
    public static Block barrel_cut_spruce = new BlockBarrelCut("barrel_cut_spruce");
    public static Block barrel_cut_birch = new BlockBarrelCut("barrel_cut_birch");
    public static Block barrel_cut_jungle = new BlockBarrelCut("barrel_cut_jungle");
    public static Block barrel_cut_acacia = new BlockBarrelCut("barrel_cut_acacia");
    public static Block barrel_cut_dark_oak = new BlockBarrelCut("barrel_cut_dark_oak");
    //BUCKET WOOD
    public static Block bucket_well_oak = new BlockBucketWell("bucket_well_oak");
    public static Block bucket_well_spruce = new BlockBucketWell("bucket_well_spruce");
    public static Block bucket_well_birch = new BlockBucketWell("bucket_well_birch");
    public static Block bucket_well_jungle = new BlockBucketWell("bucket_well_jungle");
    public static Block bucket_well_acacia = new BlockBucketWell("bucket_well_acacia");
    public static Block bucket_well_dark_oak = new BlockBucketWell("bucket_well_dark_oak");
    //PANEL WOOD
    public static Block panel_oak = new BlockPanel("panel_oak");
    public static Block panel_spruce = new BlockPanel("panel_spruce");
    public static Block panel_birch = new BlockPanel("panel_birch");
    public static Block panel_jungle = new BlockPanel("panel_jungle");
    public static Block panel_acacia = new BlockPanel("panel_acacia");
    public static Block panel_dark_oak = new BlockPanel("panel_dark_oak");
    //WAGON WHEEL
    public static Block wheel_wagon_oak = new BlockWheelWagon("wheel_wagon_oak");
    public static Block wheel_wagon_dark_oak = new BlockWheelWagon("wheel_wagon_dark_oak");
    public static Block wheel_cart_oak = new BlockWheelCart("wheel_cart_oak");
    public static Block wheel_cart_dark_oak = new BlockWheelCart("wheel_cart_dark_oak");
    //SHIP STEERING WHEEL
    public static Block wheel_ship_oak = new BlockWheelShip("wheel_ship_oak");
    public static Block wheel_ship_spruce = new BlockWheelShip("wheel_ship_spruce");
    public static Block wheel_ship_birch = new BlockWheelShip("wheel_ship_birch");
    public static Block wheel_ship_jungle = new BlockWheelShip("wheel_ship_jungle");
    public static Block wheel_ship_acacia = new BlockWheelShip("wheel_ship_acacia");
    public static Block wheel_ship_dark_oak = new BlockWheelShip("wheel_ship_dark_oak");
    //ROADS 
    public static Block road_redbrick_basketweave = new BlockRoadRedbrickBasketweave("road_redbrick_basketweave");
    public static Block road_redbrick_basketweave_slab = new BlockRoadRedbrickBasketweaveSlab("road_redbrick_basketweave_slab");
    public static Block road_stone_stackingbond_gravel = new BlockRoadStoneStackingbondGravel("road_stone_stackingbond_gravel");
    public static Block road_stone_stackingbond_gravel_slab = new BlockRoadStoneStackingbondGravelSlab("road_stone_stackingbond_gravel_slab");
    public static Block road_stone_stackingbond_stone = new BlockRoadStoneStackingbondStone("road_stone_stackingbond_stone");
    public static Block road_stone_stackingbond_stone_slab = new BlockRoadStoneStackingbondStoneSlab("road_stone_stackingbond_stone_slab");
    public static Block road_stone_stackingbond_andesite = new BlockRoadStoneStackingbondStone("road_stone_stackingbond_andesite");
    public static Block road_stone_stackingbond_andesite_slab = new BlockRoadStoneStackingbondStoneSlab("road_stone_stackingbond_andesite_slab");
    public static Block road_stone_stackingbond_diorite = new BlockRoadStoneStackingbondStone("road_stone_stackingbond_diorite");
    public static Block road_stone_stackingbond_diorite_slab = new BlockRoadStoneStackingbondStoneSlab("road_stone_stackingbond_diorite_slab");
    public static Block road_stone_stackingbond_granite = new BlockRoadStoneStackingbondStone("road_stone_stackingbond_granite");
    public static Block road_stone_stackingbond_granite_slab = new BlockRoadStoneStackingbondStoneSlab("road_stone_stackingbond_granite_slab");
    public static Block road_dirt = new BlockRoadDirt("road_dirt");
    public static Block road_dirt_slab = new BlockRoadDirtSlab("road_dirt_slab");
    public static Block road_gravel = new BlockRoadGravel("road_gravel");
    public static Block road_gravel_slab = new BlockRoadGravelSlab("road_gravel_slab");
    public static Block road_cobblestone = new BlockRoadCobblestone("road_cobblestone");
    public static Block road_cobblestone_slab = new BlockRoadCobblestoneSlab("road_cobblestone_slab");
    public static Block road_sandstone = new BlockRoadSandstone("road_sandstone");
    public static Block road_sandstone_slab = new BlockRoadSandstoneSlab("road_sandstone_slab");
    public static Block road_red_sandstone = new BlockRoadSandstone("road_red_sandstone");
    public static Block road_red_sandstone_slab = new BlockRoadSandstoneSlab("road_red_sandstone_slab");
    public static Block road_stonebrick_stackingbond = new BlockRoadStonebrickStackingbond("road_stonebrick_stackingbond");
    public static Block road_stonebrick_stackingbond_slab = new BlockRoadStonebrickStackingbondSlab("road_stonebrick_stackingbond_slab");
    //SANDSTONE HIEROGLYPHICS
    public static Block sandstone_carved_lost_one = new BlockSandstoneCarvedLost("sandstone_carved_lost_one");
    public static Block sandstone_carved_lost_two = new BlockSandstoneCarvedLost("sandstone_carved_lost_two");
    //SANDSTONE PILLARS
    public static Block sandstone_pillar = new BlockSandstonePillar("sandstone_pillar");
    public static Block red_sandstone_pillar = new BlockSandstonePillar("red_sandstone_pillar");
    //TERACOTA ROOF
	public static Block hardened_clay_roof_tile_stairs = new BlockHardenedClayStairs("hardened_clay_roof_tile_stairs");
	public static Block hardened_clay_roof_tile_white_stairs = new BlockHardenedClayStairs("hardened_clay_roof_tile_white_stairs"); 	
	public static Block hardened_clay_roof_tile_orange_stairs = new BlockHardenedClayStairs("hardened_clay_roof_tile_orange_stairs");  	
	public static Block hardened_clay_roof_tile_magenta_stairs = new BlockHardenedClayStairs("hardened_clay_roof_tile_magenta_stairs");	
	public static Block hardened_clay_roof_tile_light_blue_stairs = new BlockHardenedClayStairs("hardened_clay_roof_tile_light_blue_stairs");  	
	public static Block hardened_clay_roof_tile_yellow_stairs = new BlockHardenedClayStairs("hardened_clay_roof_tile_yellow_stairs");  	
	public static Block hardened_clay_roof_tile_lime_stairs = new BlockHardenedClayStairs("hardened_clay_roof_tile_lime_stairs");  	
	public static Block hardened_clay_roof_tile_pink_stairs = new BlockHardenedClayStairs("hardened_clay_roof_tile_pink_stairs");  	
	public static Block hardened_clay_roof_tile_grey_stairs = new BlockHardenedClayStairs("hardened_clay_roof_tile_grey_stairs");  	
	public static Block hardened_clay_roof_tile_light_grey_stairs = new BlockHardenedClayStairs("hardened_clay_roof_tile_light_grey_stairs"); 	
	public static Block hardened_clay_roof_tile_cyan_stairs = new BlockHardenedClayStairs("hardened_clay_roof_tile_cyan_stairs");	
	public static Block hardened_clay_roof_tile_purple_stairs = new BlockHardenedClayStairs("hardened_clay_roof_tile_purple_stairs");    	
	public static Block hardened_clay_roof_tile_blue_stairs = new BlockHardenedClayStairs("hardened_clay_roof_tile_blue_stairs");   	
	public static Block hardened_clay_roof_tile_brown_stairs = new BlockHardenedClayStairs("hardened_clay_roof_tile_brown_stairs");	
	public static Block hardened_clay_roof_tile_green_stairs = new BlockHardenedClayStairs("hardened_clay_roof_tile_green_stairs"); 	
	public static Block hardened_clay_roof_tile_red_stairs = new BlockHardenedClayStairs("hardened_clay_roof_tile_red_stairs");  	
	public static Block hardened_clay_roof_tile_black_stairs = new BlockHardenedClayStairs("hardened_clay_roof_tile_black_stairs"); 
	//TERACOTA ROOF ROYAL COLORS
	public static Block hardened_clay_roof_tile_royal_black_stairs = new BlockHardenedClayStairs("hardened_clay_roof_tile_royal_black_stairs");
	public static Block hardened_clay_roof_tile_royal_blue_stairs = new BlockHardenedClayStairs("hardened_clay_roof_tile_royal_blue_stairs");
	public static Block hardened_clay_roof_tile_royal_green_stairs = new BlockHardenedClayStairs("hardened_clay_roof_tile_royal_green_stairs");
	public static Block hardened_clay_roof_tile_royal_purple_stairs = new BlockHardenedClayStairs("hardened_clay_roof_tile_royal_purple_stairs");
    //COPPER ROOF
    public static Block copper_patina_roof_tile_stairs =  new BlockIronStairs("copper_patina_roof_tile_stairs");
    //METAL FENCES
	public static Block wrought_iron_bars = new BlockWroughtIronBars("wrought_iron_bars");
	public static Block iron_grate = new BlockIronGrate("iron_grate");
	public static Block wrought_iron_grate = new BlockIronGrate("wrought_iron_grate");
	public static Block iron_bars_jail = new BlockIronBarsJail("iron_bars_jail");
	public static Block wrought_iron_bars_jail = new BlockWroughtIronBars("wrought_iron_bars_jail");
	public static Block iron_bars_banner = new BlockIronBarsDesign("iron_bars_banner");
	public static Block wrought_iron_bars_banner = new BlockWroughtIronBarsDesign("wrought_iron_bars_banner");
	public static Block iron_bars_flower = new BlockIronBarsDesign("iron_bars_flower");
	public static Block wrought_iron_bars_flower = new BlockWroughtIronBarsDesign("wrought_iron_bars_flower");
	public static Block iron_bars_heart = new BlockIronBarsDesign("iron_bars_heart");
	public static Block wrought_iron_bars_heart = new BlockWroughtIronBarsDesign("wrought_iron_bars_heart");
	public static Block iron_bars_pointed = new BlockIronBarsDesign("iron_bars_pointed");
	public static Block wrought_iron_bars_pointed = new BlockWroughtIronBarsDesign("wrought_iron_bars_pointed");
	public static Block iron_bars_rolling = new BlockIronBarsDesign("iron_bars_rolling");
	public static Block wrought_iron_bars_rolling = new BlockWroughtIronBarsDesign("wrought_iron_bars_rolling");
    //ROPE
	public static Block rope_sturdy = new BlockRopeSturdy("rope_sturdy");
	public static Block rope_climbers = new BlockRopeClimbers("rope_climbers");
	public static Block rope_ladder_jacob_oak = new BlockRopeLadderJacob("rope_ladder_jacob_oak");
	public static Block rope_ladder_jacob_spruce = new BlockRopeLadderJacob("rope_ladder_jacob_spruce");
	public static Block rope_ladder_jacob_birch = new BlockRopeLadderJacob("rope_ladder_jacob_birch");
	public static Block rope_ladder_jacob_jungle = new BlockRopeLadderJacob("rope_ladder_jacob_jungle");
	public static Block rope_ladder_jacob_acacia = new BlockRopeLadderJacob("rope_ladder_jacob_acacia");
	public static Block rope_ladder_jacob_dark_oak = new BlockRopeLadderJacob("rope_ladder_jacob_dark_oak");
	//CHAIN
	public static Block chain_heavy_iron = new BlockChainHeavyIron("chain_heavy_iron");
	public static Block chain_heavy_wrought_iron = new BlockChainHeavyIron("chain_heavy_wrought_iron");
	public static Block chain_heavy_gold = new BlockChainHeavyGold("chain_heavy_gold");
	public static Block chain_light_iron = new BlockChainLightIron("chain_light_iron");
	public static Block chain_light_wrought_iron = new BlockChainLightIron("chain_light_wrought_iron");
	public static Block chain_light_gold = new BlockChainLightGold("chain_light_gold");
	//CANDLE
	public static Block candle_beeswax = new BlockCandleBeeswax("candle_beeswax");
	public static Block candle_white = new BlockCandleBeeswax("candle_white");    	
	public static Block candle_orange = new BlockCandleBeeswax("candle_orange");   	
	public static Block candle_magenta = new BlockCandleBeeswax("candle_magenta");	
	public static Block candle_light_blue = new BlockCandleBeeswax("candle_light_blue"); 	
	public static Block candle_yellow = new BlockCandleBeeswax("candle_yellow");   	
	public static Block candle_lime = new BlockCandleBeeswax("candle_lime");    	
	public static Block candle_pink = new BlockCandleBeeswax("candle_pink"); 	
	public static Block candle_grey = new BlockCandleBeeswax("candle_grey");   	
	public static Block candle_light_grey = new BlockCandleBeeswax("candle_light_grey");    	
	public static Block candle_cyan = new BlockCandleBeeswax("candle_cyan");   	
	public static Block candle_purple = new BlockCandleBeeswax("candle_purple");    	
	public static Block candle_blue = new BlockCandleBeeswax("candle_blue");   	
	public static Block candle_brown = new BlockCandleBeeswax("candle_brown");    	
	public static Block candle_green = new BlockCandleBeeswax("candle_green");    	
	public static Block candle_red = new BlockCandleBeeswax("candle_red");    	   	
	public static Block candle_black = new BlockCandleBeeswax("candle_black");
    //LANTERN
	public static Block lantern_beeswax = new BlockLanternBeeswax("lantern_beeswax");
	public static Block lantern_white = new BlockLanternBeeswax("lantern_white");    	
	public static Block lantern_orange = new BlockLanternBeeswax("lantern_orange");   	
	public static Block lantern_magenta = new BlockLanternBeeswax("lantern_magenta");	
	public static Block lantern_light_blue = new BlockLanternBeeswax("lantern_light_blue"); 	
	public static Block lantern_yellow = new BlockLanternBeeswax("lantern_yellow");   	
	public static Block lantern_lime = new BlockLanternBeeswax("lantern_lime");    	
	public static Block lantern_pink = new BlockLanternBeeswax("lantern_pink"); 	
	public static Block lantern_grey = new BlockLanternBeeswax("lantern_grey");   	
	public static Block lantern_light_grey = new BlockLanternBeeswax("lantern_light_grey");    	
	public static Block lantern_cyan = new BlockLanternBeeswax("lantern_cyan");   	
	public static Block lantern_purple = new BlockLanternBeeswax("lantern_purple");    	
	public static Block lantern_blue = new BlockLanternBeeswax("lantern_blue");   	
	public static Block lantern_brown = new BlockLanternBeeswax("lantern_brown");    	
	public static Block lantern_green = new BlockLanternBeeswax("lantern_green");    	
	public static Block lantern_red = new BlockLanternBeeswax("lantern_red");    	   	
	public static Block lantern_black = new BlockLanternBeeswax("lantern_black");

    //FOUNTAIN SQUARE
	public static Block fountain_square_stone = new BlockFountainSquareStone("fountain_square_stone");
	public static Block fountain_square_andesite = new BlockFountainSquareStone("fountain_square_andesite");
	public static Block fountain_square_diorite =  new BlockFountainSquareStone("fountain_square_diorite");
	public static Block fountain_square_granite = new BlockFountainSquareStone("fountain_square_granite");
	public static Block fountain_square_sandstone =  new BlockFountainSquareStone("fountain_square_sandstone");
	public static Block fountain_square_red_sandstone =  new BlockFountainSquareStone("fountain_square_red_sandstone");
	public static Block fountain_square_quartz =  new BlockFountainSquareStone("fountain_square_quartz");
	//FOUNTAIN TOWER
	public static Block fountain_tower_stone = new BlockFountainTowerStone("fountain_tower_stone");
	public static Block fountain_tower_andesite = new BlockFountainTowerStone("fountain_tower_andesite");
	public static Block fountain_tower_diorite =  new BlockFountainTowerStone("fountain_tower_diorite");
	public static Block fountain_tower_granite = new BlockFountainTowerStone("fountain_tower_granite");
	public static Block fountain_tower_sandstone =  new BlockFountainTowerStone("fountain_tower_sandstone");
	public static Block fountain_tower_red_sandstone =  new BlockFountainTowerStone("fountain_tower_red_sandstone");
	public static Block fountain_tower_quartz =  new BlockFountainTowerStone("fountain_tower_quartz");
	//FOUNTAIN WALL
	public static Block fountain_wall_stone = new BlockFountainWallStone("fountain_wall_stone");
	public static Block fountain_wall_andesite = new BlockFountainWallStone("fountain_wall_andesite");
	public static Block fountain_wall_diorite =  new BlockFountainWallStone("fountain_wall_diorite");
	public static Block fountain_wall_granite = new BlockFountainWallStone("fountain_wall_granite");
	public static Block fountain_wall_sandstone =  new BlockFountainWallStone("fountain_wall_sandstone");
	public static Block fountain_wall_red_sandstone =  new BlockFountainWallStone("fountain_wall_red_sandstone");
	public static Block fountain_wall_quartz =  new BlockFountainWallStone("fountain_wall_quartz");
        
	@Mod.EventBusSubscriber(modid = TyrBuilders.MODID)
	public static class RegistrationHandler 
	{
		public static List<Block> TYRBLOCKS = new ArrayList<Block>();
		
		@SubscribeEvent
		public static void register(RegistryEvent.Register<Block> event)
		{
			TYRBLOCKS.add(sugar_cube);
			TYRBLOCKS.add(charcoal_block);
			TYRBLOCKS.add(sugar_cane_block);
			TYRBLOCKS.add(sugar_cane_block_dry);
			TYRBLOCKS.add(wrought_iron_block);
			TYRBLOCKS.add(beehive);
			TYRBLOCKS.add(jar_honey);
			TYRBLOCKS.add(torch_tiki);
			TYRBLOCKS.add(torch_tiki_pole);
			TYRBLOCKS.add(straw);
			TYRBLOCKS.add(straw_stairs);
			TYRBLOCKS.add(straw_clean);
			TYRBLOCKS.add(straw_clean_stairs);
			TYRBLOCKS.add(farmland_enriched);
			TYRBLOCKS.add(glass_tempered);
			TYRBLOCKS.add(glass_tempered_white);
			TYRBLOCKS.add(glass_tempered_orange);
			TYRBLOCKS.add(glass_tempered_magenta);
			TYRBLOCKS.add(glass_tempered_light_blue);
			TYRBLOCKS.add(glass_tempered_yellow);
			TYRBLOCKS.add(glass_tempered_lime);
			TYRBLOCKS.add(glass_tempered_pink);
			TYRBLOCKS.add(glass_tempered_grey);
			TYRBLOCKS.add(glass_tempered_light_grey);
			TYRBLOCKS.add(glass_tempered_cyan);
			TYRBLOCKS.add(glass_tempered_purple);
			TYRBLOCKS.add(glass_tempered_blue);
			TYRBLOCKS.add(glass_tempered_brown);
			TYRBLOCKS.add(glass_tempered_green);
			TYRBLOCKS.add(glass_tempered_red);
			TYRBLOCKS.add(glass_tempered_black);
			TYRBLOCKS.add(glass_tempered_stairs);
			TYRBLOCKS.add(glass_tempered_white_stairs);
			TYRBLOCKS.add(glass_tempered_orange_stairs);
			TYRBLOCKS.add(glass_tempered_magenta_stairs);
			TYRBLOCKS.add(glass_tempered_light_blue_stairs);
			TYRBLOCKS.add(glass_tempered_yellow_stairs);
			TYRBLOCKS.add(glass_tempered_lime_stairs);
			TYRBLOCKS.add(glass_tempered_pink_stairs);
			TYRBLOCKS.add(glass_tempered_grey_stairs);
			TYRBLOCKS.add(glass_tempered_light_grey_stairs);
			TYRBLOCKS.add(glass_tempered_cyan_stairs);
			TYRBLOCKS.add(glass_tempered_purple_stairs);
			TYRBLOCKS.add(glass_tempered_blue_stairs);
			TYRBLOCKS.add(glass_tempered_brown_stairs);
			TYRBLOCKS.add(glass_tempered_green_stairs);
			TYRBLOCKS.add(glass_tempered_red_stairs);
			TYRBLOCKS.add(glass_tempered_black_stairs);
			TYRBLOCKS.add(glass_tempered_pane);
			TYRBLOCKS.add(glass_tempered_pane_white);
			TYRBLOCKS.add(glass_tempered_pane_orange);
			TYRBLOCKS.add(glass_tempered_pane_magenta);
			TYRBLOCKS.add(glass_tempered_pane_light_blue);
			TYRBLOCKS.add(glass_tempered_pane_yellow);
			TYRBLOCKS.add(glass_tempered_pane_lime);
			TYRBLOCKS.add(glass_tempered_pane_pink);
			TYRBLOCKS.add(glass_tempered_pane_grey);
			TYRBLOCKS.add(glass_tempered_pane_light_grey);
			TYRBLOCKS.add(glass_tempered_pane_cyan);
			TYRBLOCKS.add(glass_tempered_pane_purple);
			TYRBLOCKS.add(glass_tempered_pane_blue);
			TYRBLOCKS.add(glass_tempered_pane_brown);
			TYRBLOCKS.add(glass_tempered_pane_green);
			TYRBLOCKS.add(glass_tempered_pane_red);
			TYRBLOCKS.add(glass_tempered_pane_black);
			TYRBLOCKS.add(stone_stairs);
			TYRBLOCKS.add(stone_andesite_stairs);
			TYRBLOCKS.add(stone_diorite_stairs);
			TYRBLOCKS.add(stone_granite_stairs);
			TYRBLOCKS.add(stone_andesite_smooth_stairs);
			TYRBLOCKS.add(stone_diorite_smooth_stairs);
			TYRBLOCKS.add(stone_granite_smooth_stairs);
			TYRBLOCKS.add(hardened_clay_stairs);
			TYRBLOCKS.add(hardened_clay_stained_white_stairs);
			TYRBLOCKS.add(hardened_clay_stained_orange_stairs);
			TYRBLOCKS.add(hardened_clay_stained_magenta_stairs);
			TYRBLOCKS.add(hardened_clay_stained_light_blue_stairs);
			TYRBLOCKS.add(hardened_clay_stained_yellow_stairs);
			TYRBLOCKS.add(hardened_clay_stained_lime_stairs);
			TYRBLOCKS.add(hardened_clay_stained_pink_stairs);
			TYRBLOCKS.add(hardened_clay_stained_grey_stairs);
			TYRBLOCKS.add(hardened_clay_stained_light_grey_stairs);
			TYRBLOCKS.add(hardened_clay_stained_cyan_stairs);
			TYRBLOCKS.add(hardened_clay_stained_purple_stairs);
			TYRBLOCKS.add(hardened_clay_stained_blue_stairs);
			TYRBLOCKS.add(hardened_clay_stained_brown_stairs);
			TYRBLOCKS.add(hardened_clay_stained_green_stairs);
			TYRBLOCKS.add(hardened_clay_stained_red_stairs);
			TYRBLOCKS.add(hardened_clay_stained_black_stairs);
			TYRBLOCKS.add(stonebrick_andesite);
			TYRBLOCKS.add(stonebrick_diorite);
			TYRBLOCKS.add(stonebrick_granite);
			TYRBLOCKS.add(stonebrick_pillar);
			TYRBLOCKS.add(stone_andesite_pillar);
			TYRBLOCKS.add(stone_diorite_pillar);
			TYRBLOCKS.add(stone_granite_pillar);
			TYRBLOCKS.add(sandstone_wall);
			TYRBLOCKS.add(red_sandstone_wall);
			TYRBLOCKS.add(stone_andesite_wall);
			TYRBLOCKS.add(stone_diorite_wall);
			TYRBLOCKS.add(stone_granite_wall);
			TYRBLOCKS.add(stone_pedestal);
			TYRBLOCKS.add(stone_andesite_pedestal);
			TYRBLOCKS.add(stone_diorite_pedestal);
			TYRBLOCKS.add(stone_granite_pedestal);
			TYRBLOCKS.add(sandstone_pedestal);
			TYRBLOCKS.add(red_sandstone_pedestal);
			TYRBLOCKS.add(quartz_pedestal);
			TYRBLOCKS.add(stone_smooth_arrowslit_wall);
			TYRBLOCKS.add(stone_andesite_smooth_arrowslit_wall);
			TYRBLOCKS.add(stone_diorite_smooth_arrowslit_wall);
			TYRBLOCKS.add(stone_granite_smooth_arrowslit_wall);
			TYRBLOCKS.add(sandstone_arrowslit_wall);
			TYRBLOCKS.add(red_sandstone_arrowslit_wall);
			TYRBLOCKS.add(paper_wall_oak);
			TYRBLOCKS.add(paper_wall_spruce);
			TYRBLOCKS.add(paper_wall_birch);
			TYRBLOCKS.add(paper_wall_jungle);
			TYRBLOCKS.add(paper_wall_acacia);
			TYRBLOCKS.add(paper_wall_dark_oak);
			TYRBLOCKS.add(log_sharp_oak);
			TYRBLOCKS.add(log_sharp_spruce);
			TYRBLOCKS.add(log_sharp_birch);
			TYRBLOCKS.add(log_sharp_jungle);
			TYRBLOCKS.add(log_sharp_acacia);
			TYRBLOCKS.add(log_sharp_dark_oak);
			TYRBLOCKS.add(log_dull_oak);
			TYRBLOCKS.add(log_dull_spruce);
			TYRBLOCKS.add(log_dull_birch);
			TYRBLOCKS.add(log_dull_jungle);
			TYRBLOCKS.add(log_dull_acacia);
			TYRBLOCKS.add(log_dull_dark_oak);
			TYRBLOCKS.add(cabinet_oak_andesite);
			TYRBLOCKS.add(cabinet_spruce_andesite);
			TYRBLOCKS.add(cabinet_birch_andesite);
			TYRBLOCKS.add(cabinet_jungle_andesite);
			TYRBLOCKS.add(cabinet_acacia_andesite);
			TYRBLOCKS.add(cabinet_dark_oak_andesite);
			TYRBLOCKS.add(cabinet_oak_diorite);
			TYRBLOCKS.add(cabinet_spruce_diorite);
			TYRBLOCKS.add(cabinet_birch_diorite);
			TYRBLOCKS.add(cabinet_jungle_diorite);
			TYRBLOCKS.add(cabinet_acacia_diorite);
			TYRBLOCKS.add(cabinet_dark_oak_diorite);
			TYRBLOCKS.add(cabinet_oak_granite);
			TYRBLOCKS.add(cabinet_spruce_granite);
			TYRBLOCKS.add(cabinet_birch_granite);
			TYRBLOCKS.add(cabinet_jungle_granite);
			TYRBLOCKS.add(cabinet_acacia_granite);
			TYRBLOCKS.add(cabinet_dark_oak_granite);
			TYRBLOCKS.add(cabinet_oak_stone);
			TYRBLOCKS.add(cabinet_spruce_stone);
			TYRBLOCKS.add(cabinet_birch_stone);
			TYRBLOCKS.add(cabinet_jungle_stone);
			TYRBLOCKS.add(cabinet_acacia_stone);
			TYRBLOCKS.add(cabinet_dark_oak_stone);
			TYRBLOCKS.add(cabinet_drawers_oak_andesite);
			TYRBLOCKS.add(cabinet_drawers_spruce_andesite);
			TYRBLOCKS.add(cabinet_drawers_birch_andesite);
			TYRBLOCKS.add(cabinet_drawers_jungle_andesite);
			TYRBLOCKS.add(cabinet_drawers_acacia_andesite);
			TYRBLOCKS.add(cabinet_drawers_dark_oak_andesite);
			TYRBLOCKS.add(cabinet_drawers_oak_diorite);
			TYRBLOCKS.add(cabinet_drawers_spruce_diorite);
			TYRBLOCKS.add(cabinet_drawers_birch_diorite);
			TYRBLOCKS.add(cabinet_drawers_jungle_diorite);
			TYRBLOCKS.add(cabinet_drawers_acacia_diorite);
			TYRBLOCKS.add(cabinet_drawers_dark_oak_diorite);
			TYRBLOCKS.add(cabinet_drawers_oak_granite);
			TYRBLOCKS.add(cabinet_drawers_spruce_granite);
			TYRBLOCKS.add(cabinet_drawers_birch_granite);
			TYRBLOCKS.add(cabinet_drawers_jungle_granite);
			TYRBLOCKS.add(cabinet_drawers_acacia_granite);
			TYRBLOCKS.add(cabinet_drawers_dark_oak_granite);
			TYRBLOCKS.add(cabinet_drawers_oak_stone);
			TYRBLOCKS.add(cabinet_drawers_spruce_stone);
			TYRBLOCKS.add(cabinet_drawers_birch_stone);
			TYRBLOCKS.add(cabinet_drawers_jungle_stone);
			TYRBLOCKS.add(cabinet_drawers_acacia_stone);
			TYRBLOCKS.add(cabinet_drawers_dark_oak_stone);
			TYRBLOCKS.add(cabinet_doors_oak);
			TYRBLOCKS.add(cabinet_doors_spruce);
			TYRBLOCKS.add(cabinet_doors_birch);
			TYRBLOCKS.add(cabinet_doors_jungle);
			TYRBLOCKS.add(cabinet_doors_acacia);
			TYRBLOCKS.add(cabinet_doors_dark_oak);
			TYRBLOCKS.add(crate_small_oak);
			TYRBLOCKS.add(crate_small_spruce);
			TYRBLOCKS.add(crate_small_birch);
			TYRBLOCKS.add(crate_small_jungle);
			TYRBLOCKS.add(crate_small_acacia);
			TYRBLOCKS.add(crate_small_dark_oak);
			TYRBLOCKS.add(crate_oak);
			TYRBLOCKS.add(crate_spruce);
			TYRBLOCKS.add(crate_birch);
			TYRBLOCKS.add(crate_jungle);
			TYRBLOCKS.add(crate_acacia);
			TYRBLOCKS.add(crate_dark_oak);
			TYRBLOCKS.add(barrel_oak);
			TYRBLOCKS.add(barrel_spruce);
			TYRBLOCKS.add(barrel_birch);
			TYRBLOCKS.add(barrel_jungle);
			TYRBLOCKS.add(barrel_acacia);
			TYRBLOCKS.add(barrel_dark_oak);
			TYRBLOCKS.add(barrel_cut_oak);
			TYRBLOCKS.add(barrel_cut_spruce);
			TYRBLOCKS.add(barrel_cut_birch);
			TYRBLOCKS.add(barrel_cut_jungle);
			TYRBLOCKS.add(barrel_cut_acacia);
			TYRBLOCKS.add(barrel_cut_dark_oak);
			TYRBLOCKS.add(bucket_well_oak);
			TYRBLOCKS.add(bucket_well_spruce);
			TYRBLOCKS.add(bucket_well_birch);
			TYRBLOCKS.add(bucket_well_jungle);
			TYRBLOCKS.add(bucket_well_acacia);
			TYRBLOCKS.add(bucket_well_dark_oak);
			TYRBLOCKS.add(panel_oak);
			TYRBLOCKS.add(panel_spruce);
			TYRBLOCKS.add(panel_birch);
			TYRBLOCKS.add(panel_jungle);
			TYRBLOCKS.add(panel_acacia);
			TYRBLOCKS.add(panel_dark_oak);
			TYRBLOCKS.add(wheel_wagon_oak);
			TYRBLOCKS.add(wheel_wagon_dark_oak);
			TYRBLOCKS.add(wheel_cart_oak);
			TYRBLOCKS.add(wheel_cart_dark_oak);
			TYRBLOCKS.add(wheel_ship_oak);
			TYRBLOCKS.add(wheel_ship_spruce);
			TYRBLOCKS.add(wheel_ship_birch);
			TYRBLOCKS.add(wheel_ship_jungle);
			TYRBLOCKS.add(wheel_ship_acacia);
			TYRBLOCKS.add(wheel_ship_dark_oak);
			TYRBLOCKS.add(road_dirt);
			TYRBLOCKS.add(road_dirt_slab);
			TYRBLOCKS.add(road_gravel);
			TYRBLOCKS.add(road_gravel_slab);
			TYRBLOCKS.add(road_cobblestone);
			TYRBLOCKS.add(road_cobblestone_slab);
			TYRBLOCKS.add(road_stone_stackingbond_gravel);
			TYRBLOCKS.add(road_stone_stackingbond_gravel_slab);
			TYRBLOCKS.add(road_redbrick_basketweave);
			TYRBLOCKS.add(road_redbrick_basketweave_slab);
			TYRBLOCKS.add(road_stone_stackingbond_stone);
			TYRBLOCKS.add(road_stone_stackingbond_stone_slab);
			TYRBLOCKS.add(road_stone_stackingbond_andesite);
			TYRBLOCKS.add(road_stone_stackingbond_andesite_slab);
			TYRBLOCKS.add(road_stone_stackingbond_diorite);
			TYRBLOCKS.add(road_stone_stackingbond_diorite_slab);
			TYRBLOCKS.add(road_stone_stackingbond_granite);
			TYRBLOCKS.add(road_stone_stackingbond_granite_slab);
			TYRBLOCKS.add(road_sandstone);
			TYRBLOCKS.add(road_sandstone_slab);
			TYRBLOCKS.add(road_red_sandstone);
			TYRBLOCKS.add(road_red_sandstone_slab);
			TYRBLOCKS.add(road_stonebrick_stackingbond);
			TYRBLOCKS.add(road_stonebrick_stackingbond_slab);
			TYRBLOCKS.add(sandstone_carved_lost_one);
			TYRBLOCKS.add(sandstone_carved_lost_two);
			TYRBLOCKS.add(sandstone_pillar);
			TYRBLOCKS.add(red_sandstone_pillar);
//			TYRBLOCKS.add(stringer_spacer);
//			TYRBLOCKS.add(stringer_white_triangle);
//			TYRBLOCKS.add(stringer_orange_triangle);
//			TYRBLOCKS.add(stringer_magenta_triangle);
//			TYRBLOCKS.add(stringer_light_blue_triangle);
//			TYRBLOCKS.add(stringer_yellow_triangle);
//			TYRBLOCKS.add(stringer_lime_triangle);
//			TYRBLOCKS.add(stringer_pink_triangle);
//			TYRBLOCKS.add(stringer_grey_triangle);
//			TYRBLOCKS.add(stringer_light_grey_triangle);
//			TYRBLOCKS.add(stringer_cyan_triangle);
//			TYRBLOCKS.add(stringer_purple_triangle);
//			TYRBLOCKS.add(stringer_blue_triangle);
//			TYRBLOCKS.add(stringer_brown_triangle);
//			TYRBLOCKS.add(stringer_green_triangle);
//			TYRBLOCKS.add(stringer_red_triangle);
//			TYRBLOCKS.add(stringer_black_triangle);
//			TYRBLOCKS.add(stringer_white_dovetail);
//			TYRBLOCKS.add(stringer_orange_dovetail);
//			TYRBLOCKS.add(stringer_magenta_dovetail);
//			TYRBLOCKS.add(stringer_light_blue_dovetail);
//			TYRBLOCKS.add(stringer_yellow_dovetail);
//			TYRBLOCKS.add(stringer_lime_dovetail);
//			TYRBLOCKS.add(stringer_pink_dovetail);
//			TYRBLOCKS.add(stringer_grey_dovetail);
//			TYRBLOCKS.add(stringer_light_grey_dovetail);
//			TYRBLOCKS.add(stringer_cyan_dovetail);
//			TYRBLOCKS.add(stringer_purple_dovetail);
//			TYRBLOCKS.add(stringer_blue_dovetail);
//			TYRBLOCKS.add(stringer_brown_dovetail);
//			TYRBLOCKS.add(stringer_green_dovetail);
//			TYRBLOCKS.add(stringer_red_dovetail);
//			TYRBLOCKS.add(stringer_black_dovetail);
			
			TYRBLOCKS.add(hardened_clay_roof_tile_stairs);
			TYRBLOCKS.add(hardened_clay_roof_tile_white_stairs);
			TYRBLOCKS.add(hardened_clay_roof_tile_orange_stairs);
			TYRBLOCKS.add(hardened_clay_roof_tile_magenta_stairs);
			TYRBLOCKS.add(hardened_clay_roof_tile_light_blue_stairs);
			TYRBLOCKS.add(hardened_clay_roof_tile_yellow_stairs);
			TYRBLOCKS.add(hardened_clay_roof_tile_lime_stairs);
			TYRBLOCKS.add(hardened_clay_roof_tile_pink_stairs);
			TYRBLOCKS.add(hardened_clay_roof_tile_grey_stairs);
			TYRBLOCKS.add(hardened_clay_roof_tile_light_grey_stairs);
			TYRBLOCKS.add(hardened_clay_roof_tile_cyan_stairs);
			TYRBLOCKS.add(hardened_clay_roof_tile_purple_stairs);
			TYRBLOCKS.add(hardened_clay_roof_tile_blue_stairs);
			TYRBLOCKS.add(hardened_clay_roof_tile_brown_stairs);
			TYRBLOCKS.add(hardened_clay_roof_tile_green_stairs);
			TYRBLOCKS.add(hardened_clay_roof_tile_red_stairs);
			TYRBLOCKS.add(hardened_clay_roof_tile_black_stairs);
			TYRBLOCKS.add(hardened_clay_roof_tile_royal_black_stairs);
			TYRBLOCKS.add(hardened_clay_roof_tile_royal_blue_stairs);
			TYRBLOCKS.add(hardened_clay_roof_tile_royal_green_stairs);
			TYRBLOCKS.add(hardened_clay_roof_tile_royal_purple_stairs);		
			TYRBLOCKS.add(copper_patina_roof_tile_stairs);
			TYRBLOCKS.add(wrought_iron_bars);
			TYRBLOCKS.add(iron_grate);
			TYRBLOCKS.add(wrought_iron_grate);
			TYRBLOCKS.add(iron_bars_jail);
			TYRBLOCKS.add(wrought_iron_bars_jail);
			TYRBLOCKS.add(iron_bars_banner);
			TYRBLOCKS.add(wrought_iron_bars_banner);
			TYRBLOCKS.add(iron_bars_flower);
			TYRBLOCKS.add(wrought_iron_bars_flower);
			TYRBLOCKS.add(iron_bars_heart);
			TYRBLOCKS.add(wrought_iron_bars_heart);
			TYRBLOCKS.add(iron_bars_pointed);
			TYRBLOCKS.add(wrought_iron_bars_pointed);
			TYRBLOCKS.add(iron_bars_rolling);
			TYRBLOCKS.add(wrought_iron_bars_rolling);
			TYRBLOCKS.add(rope_sturdy);
			TYRBLOCKS.add(rope_climbers);
			TYRBLOCKS.add(rope_ladder_jacob_oak);
			TYRBLOCKS.add(rope_ladder_jacob_spruce);
			TYRBLOCKS.add(rope_ladder_jacob_birch);
			TYRBLOCKS.add(rope_ladder_jacob_jungle);
			TYRBLOCKS.add(rope_ladder_jacob_acacia);
			TYRBLOCKS.add(rope_ladder_jacob_dark_oak);
			TYRBLOCKS.add(chain_heavy_iron);
			TYRBLOCKS.add(chain_heavy_wrought_iron);
			TYRBLOCKS.add(chain_heavy_gold);
			TYRBLOCKS.add(chain_light_iron);
			TYRBLOCKS.add(chain_light_wrought_iron);
			TYRBLOCKS.add(chain_light_gold);
			TYRBLOCKS.add(candle_beeswax);
			TYRBLOCKS.add(candle_white);
			TYRBLOCKS.add(candle_orange);
			TYRBLOCKS.add(candle_magenta);
			TYRBLOCKS.add(candle_light_blue);
			TYRBLOCKS.add(candle_yellow);
			TYRBLOCKS.add(candle_lime);
			TYRBLOCKS.add(candle_pink);
			TYRBLOCKS.add(candle_grey);
			TYRBLOCKS.add(candle_light_grey);
			TYRBLOCKS.add(candle_cyan);
			TYRBLOCKS.add(candle_purple);
			TYRBLOCKS.add(candle_blue);
			TYRBLOCKS.add(candle_brown);
			TYRBLOCKS.add(candle_green);
			TYRBLOCKS.add(candle_red);
			TYRBLOCKS.add(candle_black);
			TYRBLOCKS.add(lantern_beeswax);
			TYRBLOCKS.add(lantern_white);
			TYRBLOCKS.add(lantern_orange);
			TYRBLOCKS.add(lantern_magenta);
			TYRBLOCKS.add(lantern_light_blue);
			TYRBLOCKS.add(lantern_yellow);
			TYRBLOCKS.add(lantern_lime);
			TYRBLOCKS.add(lantern_pink);
			TYRBLOCKS.add(lantern_grey);
			TYRBLOCKS.add(lantern_light_grey);
			TYRBLOCKS.add(lantern_cyan);
			TYRBLOCKS.add(lantern_purple);
			TYRBLOCKS.add(lantern_blue);
			TYRBLOCKS.add(lantern_brown);
			TYRBLOCKS.add(lantern_green);
			TYRBLOCKS.add(lantern_red);
			TYRBLOCKS.add(lantern_black);
			TYRBLOCKS.add(fountain_square_stone);
			TYRBLOCKS.add(fountain_square_andesite);
			TYRBLOCKS.add(fountain_square_diorite);
			TYRBLOCKS.add(fountain_square_granite);
			TYRBLOCKS.add(fountain_square_sandstone);
			TYRBLOCKS.add(fountain_square_red_sandstone);
			TYRBLOCKS.add(fountain_square_quartz);
			TYRBLOCKS.add(fountain_tower_stone);
			TYRBLOCKS.add(fountain_tower_andesite);
			TYRBLOCKS.add(fountain_tower_diorite);
			TYRBLOCKS.add(fountain_tower_granite);
			TYRBLOCKS.add(fountain_tower_sandstone);
			TYRBLOCKS.add(fountain_tower_red_sandstone);
			TYRBLOCKS.add(fountain_tower_quartz);
			TYRBLOCKS.add(fountain_wall_stone);
			TYRBLOCKS.add(fountain_wall_andesite);
			TYRBLOCKS.add(fountain_wall_diorite);
			TYRBLOCKS.add(fountain_wall_granite);
			TYRBLOCKS.add(fountain_wall_sandstone);
			TYRBLOCKS.add(fountain_wall_red_sandstone);
			TYRBLOCKS.add(fountain_wall_quartz);

			for(Block block : TYRBLOCKS)
			{
	            event.getRegistry().register(block);
	        }
			
			registerBlockSlab(straw_slab, new ItemSlab(straw_slab, straw_slab, straw_slab_double));
			ForgeRegistries.BLOCKS.register(straw_slab_double);
			registerBlockSlab(straw_clean_slab, new ItemSlab(straw_clean_slab, straw_clean_slab, straw_clean_slab_double));
			ForgeRegistries.BLOCKS.register(straw_clean_slab_double);
			//TEMPERED GLASS SLABS
			registerBlockSlab(glass_tempered_slab, new ItemSlab(glass_tempered_slab, glass_tempered_slab, glass_tempered_slab_double));
			ForgeRegistries.BLOCKS.register(glass_tempered_slab_double);
			registerBlockSlab(glass_tempered_white_slab, new ItemSlab(glass_tempered_white_slab, glass_tempered_white_slab, glass_tempered_white_slab_double));
			ForgeRegistries.BLOCKS.register(glass_tempered_white_slab_double);
			registerBlockSlab(glass_tempered_orange_slab, new ItemSlab(glass_tempered_orange_slab, glass_tempered_orange_slab, glass_tempered_orange_slab_double));
			ForgeRegistries.BLOCKS.register(glass_tempered_orange_slab_double);
			registerBlockSlab(glass_tempered_magenta_slab, new ItemSlab(glass_tempered_magenta_slab, glass_tempered_magenta_slab, glass_tempered_magenta_slab_double));
			ForgeRegistries.BLOCKS.register(glass_tempered_magenta_slab_double);
			registerBlockSlab(glass_tempered_light_blue_slab, new ItemSlab(glass_tempered_light_blue_slab, glass_tempered_light_blue_slab, glass_tempered_light_blue_slab_double));
			ForgeRegistries.BLOCKS.register(glass_tempered_light_blue_slab_double);
			registerBlockSlab(glass_tempered_yellow_slab, new ItemSlab(glass_tempered_yellow_slab, glass_tempered_yellow_slab, glass_tempered_yellow_slab_double));
			ForgeRegistries.BLOCKS.register(glass_tempered_yellow_slab_double);
			registerBlockSlab(glass_tempered_lime_slab, new ItemSlab(glass_tempered_lime_slab, glass_tempered_lime_slab, glass_tempered_lime_slab_double));
			ForgeRegistries.BLOCKS.register(glass_tempered_lime_slab_double);
			registerBlockSlab(glass_tempered_pink_slab, new ItemSlab(glass_tempered_pink_slab, glass_tempered_pink_slab, glass_tempered_pink_slab_double));
			ForgeRegistries.BLOCKS.register(glass_tempered_pink_slab_double);
			registerBlockSlab(glass_tempered_grey_slab, new ItemSlab(glass_tempered_grey_slab, glass_tempered_grey_slab, glass_tempered_grey_slab_double));
			ForgeRegistries.BLOCKS.register(glass_tempered_grey_slab_double);
			registerBlockSlab(glass_tempered_light_grey_slab, new ItemSlab(glass_tempered_light_grey_slab, glass_tempered_light_grey_slab, glass_tempered_light_grey_slab_double));
			ForgeRegistries.BLOCKS.register(glass_tempered_light_grey_slab_double);
			registerBlockSlab(glass_tempered_cyan_slab, new ItemSlab(glass_tempered_cyan_slab, glass_tempered_cyan_slab, glass_tempered_cyan_slab_double));
			ForgeRegistries.BLOCKS.register(glass_tempered_cyan_slab_double);
			registerBlockSlab(glass_tempered_purple_slab, new ItemSlab(glass_tempered_purple_slab, glass_tempered_purple_slab, glass_tempered_purple_slab_double));
			ForgeRegistries.BLOCKS.register(glass_tempered_purple_slab_double);
			registerBlockSlab(glass_tempered_blue_slab, new ItemSlab(glass_tempered_blue_slab, glass_tempered_blue_slab, glass_tempered_blue_slab_double));
			ForgeRegistries.BLOCKS.register(glass_tempered_blue_slab_double);
			registerBlockSlab(glass_tempered_brown_slab, new ItemSlab(glass_tempered_brown_slab, glass_tempered_brown_slab, glass_tempered_brown_slab_double));
			ForgeRegistries.BLOCKS.register(glass_tempered_brown_slab_double);
			registerBlockSlab(glass_tempered_green_slab, new ItemSlab(glass_tempered_green_slab, glass_tempered_green_slab, glass_tempered_green_slab_double));
			ForgeRegistries.BLOCKS.register(glass_tempered_green_slab_double);
			registerBlockSlab(glass_tempered_red_slab, new ItemSlab(glass_tempered_red_slab, glass_tempered_red_slab, glass_tempered_red_slab_double));
			ForgeRegistries.BLOCKS.register(glass_tempered_red_slab_double);
			registerBlockSlab(glass_tempered_black_slab, new ItemSlab(glass_tempered_black_slab, glass_tempered_black_slab, glass_tempered_black_slab_double));
			ForgeRegistries.BLOCKS.register(glass_tempered_black_slab_double);
			//HARDENED CLAY STAINED SLABS
			registerBlockSlab(hardened_clay_stained_slab, new ItemSlab(hardened_clay_stained_slab, hardened_clay_stained_slab, hardened_clay_stained_slab_double));
			ForgeRegistries.BLOCKS.register(hardened_clay_stained_slab_double);
			registerBlockSlab(hardened_clay_stained_white_slab, new ItemSlab(hardened_clay_stained_white_slab, hardened_clay_stained_white_slab, hardened_clay_stained_white_slab_double));
			ForgeRegistries.BLOCKS.register(hardened_clay_stained_white_slab_double);
			registerBlockSlab(hardened_clay_stained_orange_slab, new ItemSlab(hardened_clay_stained_orange_slab, hardened_clay_stained_orange_slab, hardened_clay_stained_orange_slab_double));
			ForgeRegistries.BLOCKS.register(hardened_clay_stained_orange_slab_double);
			registerBlockSlab(hardened_clay_stained_magenta_slab, new ItemSlab(hardened_clay_stained_magenta_slab, hardened_clay_stained_magenta_slab, hardened_clay_stained_magenta_slab_double));
			ForgeRegistries.BLOCKS.register(hardened_clay_stained_magenta_slab_double);
			registerBlockSlab(hardened_clay_stained_light_blue_slab, new ItemSlab(hardened_clay_stained_light_blue_slab, hardened_clay_stained_light_blue_slab, hardened_clay_stained_light_blue_slab_double));
			ForgeRegistries.BLOCKS.register(hardened_clay_stained_light_blue_slab_double);
			registerBlockSlab(hardened_clay_stained_yellow_slab, new ItemSlab(hardened_clay_stained_yellow_slab, hardened_clay_stained_yellow_slab, hardened_clay_stained_yellow_slab_double));
			ForgeRegistries.BLOCKS.register(hardened_clay_stained_yellow_slab_double);
			registerBlockSlab(hardened_clay_stained_lime_slab, new ItemSlab(hardened_clay_stained_lime_slab, hardened_clay_stained_lime_slab, hardened_clay_stained_lime_slab_double));
			ForgeRegistries.BLOCKS.register(hardened_clay_stained_lime_slab_double);
			registerBlockSlab(hardened_clay_stained_pink_slab, new ItemSlab(hardened_clay_stained_pink_slab, hardened_clay_stained_pink_slab, hardened_clay_stained_pink_slab_double));
			ForgeRegistries.BLOCKS.register(hardened_clay_stained_pink_slab_double);
			registerBlockSlab(hardened_clay_stained_grey_slab, new ItemSlab(hardened_clay_stained_grey_slab, hardened_clay_stained_grey_slab, hardened_clay_stained_grey_slab_double));
			ForgeRegistries.BLOCKS.register(hardened_clay_stained_grey_slab_double);
			registerBlockSlab(hardened_clay_stained_light_grey_slab, new ItemSlab(hardened_clay_stained_light_grey_slab, hardened_clay_stained_light_grey_slab, hardened_clay_stained_light_grey_slab_double));
			ForgeRegistries.BLOCKS.register(hardened_clay_stained_light_grey_slab_double);
			registerBlockSlab(hardened_clay_stained_cyan_slab, new ItemSlab(hardened_clay_stained_cyan_slab, hardened_clay_stained_cyan_slab, hardened_clay_stained_cyan_slab_double));
			ForgeRegistries.BLOCKS.register(hardened_clay_stained_cyan_slab_double);
			registerBlockSlab(hardened_clay_stained_purple_slab, new ItemSlab(hardened_clay_stained_purple_slab, hardened_clay_stained_purple_slab, hardened_clay_stained_purple_slab_double));
			ForgeRegistries.BLOCKS.register(hardened_clay_stained_purple_slab_double);
			registerBlockSlab(hardened_clay_stained_blue_slab, new ItemSlab(hardened_clay_stained_blue_slab, hardened_clay_stained_blue_slab, hardened_clay_stained_blue_slab_double));
			ForgeRegistries.BLOCKS.register(hardened_clay_stained_blue_slab_double);
			registerBlockSlab(hardened_clay_stained_brown_slab, new ItemSlab(hardened_clay_stained_brown_slab, hardened_clay_stained_brown_slab, hardened_clay_stained_brown_slab_double));
			ForgeRegistries.BLOCKS.register(hardened_clay_stained_brown_slab_double);
			registerBlockSlab(hardened_clay_stained_green_slab, new ItemSlab(hardened_clay_stained_green_slab, hardened_clay_stained_green_slab, hardened_clay_stained_green_slab_double));
			ForgeRegistries.BLOCKS.register(hardened_clay_stained_green_slab_double);
			registerBlockSlab(hardened_clay_stained_red_slab, new ItemSlab(hardened_clay_stained_red_slab, hardened_clay_stained_red_slab, hardened_clay_stained_red_slab_double));
			ForgeRegistries.BLOCKS.register(hardened_clay_stained_red_slab_double);
			registerBlockSlab(hardened_clay_stained_black_slab, new ItemSlab(hardened_clay_stained_black_slab, hardened_clay_stained_black_slab, hardened_clay_stained_black_slab_double));
			ForgeRegistries.BLOCKS.register(hardened_clay_stained_black_slab_double);
			//WOOL SLABS
			registerBlockSlab(wool_white_slab, new ItemSlab(wool_white_slab, wool_white_slab, wool_white_slab_double));
			ForgeRegistries.BLOCKS.register(wool_white_slab_double);
			registerBlockSlab(wool_orange_slab, new ItemSlab(wool_orange_slab, wool_orange_slab, wool_orange_slab_double));
			ForgeRegistries.BLOCKS.register(wool_orange_slab_double);
			registerBlockSlab(wool_magenta_slab, new ItemSlab(wool_magenta_slab, wool_magenta_slab, wool_magenta_slab_double));
			ForgeRegistries.BLOCKS.register(wool_magenta_slab_double);
			registerBlockSlab(wool_light_blue_slab, new ItemSlab(wool_light_blue_slab, wool_light_blue_slab, wool_light_blue_slab_double));
			ForgeRegistries.BLOCKS.register(wool_light_blue_slab_double);
			registerBlockSlab(wool_yellow_slab, new ItemSlab(wool_yellow_slab, wool_yellow_slab, wool_yellow_slab_double));
			ForgeRegistries.BLOCKS.register(wool_yellow_slab_double);
			registerBlockSlab(wool_lime_slab, new ItemSlab(wool_lime_slab, wool_lime_slab, wool_lime_slab_double));
			ForgeRegistries.BLOCKS.register(wool_lime_slab_double);
			registerBlockSlab(wool_pink_slab, new ItemSlab(wool_pink_slab, wool_pink_slab, wool_pink_slab_double));
			ForgeRegistries.BLOCKS.register(wool_pink_slab_double);
			registerBlockSlab(wool_grey_slab, new ItemSlab(wool_grey_slab, wool_grey_slab, wool_grey_slab_double));
			ForgeRegistries.BLOCKS.register(wool_grey_slab_double);
			registerBlockSlab(wool_light_grey_slab, new ItemSlab(wool_light_grey_slab, wool_light_grey_slab, wool_light_grey_slab_double));
			ForgeRegistries.BLOCKS.register(wool_light_grey_slab_double);
			registerBlockSlab(wool_cyan_slab, new ItemSlab(wool_cyan_slab, wool_cyan_slab, wool_cyan_slab_double));
			ForgeRegistries.BLOCKS.register(wool_cyan_slab_double);
			registerBlockSlab(wool_purple_slab, new ItemSlab(wool_purple_slab, wool_purple_slab, wool_purple_slab_double));
			ForgeRegistries.BLOCKS.register(wool_purple_slab_double);
			registerBlockSlab(wool_blue_slab, new ItemSlab(wool_blue_slab, wool_blue_slab, wool_blue_slab_double));
			ForgeRegistries.BLOCKS.register(wool_blue_slab_double);
			registerBlockSlab(wool_brown_slab, new ItemSlab(wool_brown_slab, wool_brown_slab, wool_brown_slab_double));
			ForgeRegistries.BLOCKS.register(wool_brown_slab_double);
			registerBlockSlab(wool_green_slab, new ItemSlab(wool_green_slab, wool_green_slab, wool_green_slab_double));
			ForgeRegistries.BLOCKS.register(wool_green_slab_double);
			registerBlockSlab(wool_red_slab, new ItemSlab(wool_red_slab, wool_red_slab, wool_red_slab_double));
			ForgeRegistries.BLOCKS.register(wool_red_slab_double);
			registerBlockSlab(wool_black_slab, new ItemSlab(wool_black_slab, wool_black_slab, wool_black_slab_double));
			ForgeRegistries.BLOCKS.register(wool_black_slab_double);
			//STONE SLABS
			registerBlockSlab(mossy_cobblestone_slab, new ItemSlab(mossy_cobblestone_slab, mossy_cobblestone_slab, mossy_cobblestone_slab_double));
			ForgeRegistries.BLOCKS.register(mossy_cobblestone_slab_double);
			registerBlockSlab(stone_andesite_slab , new ItemSlab(stone_andesite_slab , stone_andesite_slab , stone_andesite_slab_double));
			ForgeRegistries.BLOCKS.register(stone_andesite_slab_double);
			registerBlockSlab(stone_diorite_slab , new ItemSlab(stone_diorite_slab , stone_diorite_slab , stone_diorite_slab_double));
			ForgeRegistries.BLOCKS.register(stone_diorite_slab_double);
			registerBlockSlab(stone_granite_slab , new ItemSlab(stone_granite_slab , stone_granite_slab , stone_granite_slab_double));
			ForgeRegistries.BLOCKS.register(stone_granite_slab_double);
			registerBlockSlab(stone_andesite_smooth_slab , new ItemSlab(stone_andesite_smooth_slab , stone_andesite_smooth_slab , stone_andesite_smooth_slab_double));
			ForgeRegistries.BLOCKS.register(stone_andesite_smooth_slab_double);
			registerBlockSlab(stone_diorite_smooth_slab , new ItemSlab(stone_diorite_smooth_slab , stone_diorite_smooth_slab , stone_diorite_smooth_slab_double));
			ForgeRegistries.BLOCKS.register(stone_diorite_smooth_slab_double);
			registerBlockSlab(stone_granite_smooth_slab , new ItemSlab(stone_granite_smooth_slab , stone_granite_smooth_slab , stone_granite_smooth_slab_double));
			ForgeRegistries.BLOCKS.register(stone_granite_smooth_slab_double);
		}
					
	    @SubscribeEvent
	    public static void registerItemBlocks(RegistryEvent.Register<Item> event)
	    {
	        for(Block block: TYRBLOCKS)
	        {
	            event.getRegistry().register(new ItemBlock(block).setRegistryName(block.getRegistryName()));
	        }
	    }
	    
		@SubscribeEvent
		public static void registerModels(ModelRegistryEvent event)
		{			
			for(Block block : TYRBLOCKS)
			{
				ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(block), 0, new ModelResourceLocation(block.getRegistryName(), "inventory"));
	        }
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(straw_slab), 0, new ModelResourceLocation(straw_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(straw_clean_slab), 0, new ModelResourceLocation(straw_clean_slab.getRegistryName(), "inventory"));
			//TEMPERED GLASS SLABS
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(glass_tempered_slab), 0, new ModelResourceLocation(glass_tempered_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(glass_tempered_white_slab), 0, new ModelResourceLocation(glass_tempered_white_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(glass_tempered_orange_slab), 0, new ModelResourceLocation(glass_tempered_orange_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(glass_tempered_magenta_slab), 0, new ModelResourceLocation(glass_tempered_magenta_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(glass_tempered_light_blue_slab), 0, new ModelResourceLocation(glass_tempered_light_blue_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(glass_tempered_yellow_slab), 0, new ModelResourceLocation(glass_tempered_yellow_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(glass_tempered_lime_slab), 0, new ModelResourceLocation(glass_tempered_lime_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(glass_tempered_pink_slab), 0, new ModelResourceLocation(glass_tempered_pink_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(glass_tempered_grey_slab), 0, new ModelResourceLocation(glass_tempered_grey_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(glass_tempered_light_grey_slab), 0, new ModelResourceLocation(glass_tempered_light_grey_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(glass_tempered_cyan_slab), 0, new ModelResourceLocation(glass_tempered_cyan_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(glass_tempered_purple_slab), 0, new ModelResourceLocation(glass_tempered_purple_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(glass_tempered_blue_slab), 0, new ModelResourceLocation(glass_tempered_blue_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(glass_tempered_brown_slab), 0, new ModelResourceLocation(glass_tempered_brown_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(glass_tempered_green_slab), 0, new ModelResourceLocation(glass_tempered_green_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(glass_tempered_red_slab), 0, new ModelResourceLocation(glass_tempered_red_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(glass_tempered_black_slab), 0, new ModelResourceLocation(glass_tempered_black_slab.getRegistryName(), "inventory"));
			//HARDENED CLAY STAINED SLABS
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(hardened_clay_stained_slab), 0, new ModelResourceLocation(hardened_clay_stained_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(hardened_clay_stained_white_slab), 0, new ModelResourceLocation(hardened_clay_stained_white_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(hardened_clay_stained_orange_slab), 0, new ModelResourceLocation(hardened_clay_stained_orange_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(hardened_clay_stained_magenta_slab), 0, new ModelResourceLocation(hardened_clay_stained_magenta_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(hardened_clay_stained_light_blue_slab), 0, new ModelResourceLocation(hardened_clay_stained_light_blue_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(hardened_clay_stained_yellow_slab), 0, new ModelResourceLocation(hardened_clay_stained_yellow_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(hardened_clay_stained_lime_slab), 0, new ModelResourceLocation(hardened_clay_stained_lime_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(hardened_clay_stained_pink_slab), 0, new ModelResourceLocation(hardened_clay_stained_pink_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(hardened_clay_stained_grey_slab), 0, new ModelResourceLocation(hardened_clay_stained_grey_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(hardened_clay_stained_light_grey_slab), 0, new ModelResourceLocation(hardened_clay_stained_light_grey_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(hardened_clay_stained_cyan_slab), 0, new ModelResourceLocation(hardened_clay_stained_cyan_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(hardened_clay_stained_purple_slab), 0, new ModelResourceLocation(hardened_clay_stained_purple_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(hardened_clay_stained_blue_slab), 0, new ModelResourceLocation(hardened_clay_stained_blue_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(hardened_clay_stained_brown_slab), 0, new ModelResourceLocation(hardened_clay_stained_brown_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(hardened_clay_stained_green_slab), 0, new ModelResourceLocation(hardened_clay_stained_green_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(hardened_clay_stained_red_slab), 0, new ModelResourceLocation(hardened_clay_stained_red_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(hardened_clay_stained_black_slab), 0, new ModelResourceLocation(hardened_clay_stained_black_slab.getRegistryName(), "inventory"));
			//WOOL SLABS
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(wool_white_slab), 0, new ModelResourceLocation(wool_white_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(wool_orange_slab), 0, new ModelResourceLocation(wool_orange_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(wool_magenta_slab), 0, new ModelResourceLocation(wool_magenta_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(wool_light_blue_slab), 0, new ModelResourceLocation(wool_light_blue_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(wool_yellow_slab), 0, new ModelResourceLocation(wool_yellow_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(wool_lime_slab), 0, new ModelResourceLocation(wool_lime_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(wool_pink_slab), 0, new ModelResourceLocation(wool_pink_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(wool_grey_slab), 0, new ModelResourceLocation(wool_grey_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(wool_light_grey_slab), 0, new ModelResourceLocation(wool_light_grey_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(wool_cyan_slab), 0, new ModelResourceLocation(wool_cyan_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(wool_purple_slab), 0, new ModelResourceLocation(wool_purple_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(wool_blue_slab), 0, new ModelResourceLocation(wool_blue_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(wool_brown_slab), 0, new ModelResourceLocation(wool_brown_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(wool_green_slab), 0, new ModelResourceLocation(wool_green_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(wool_red_slab), 0, new ModelResourceLocation(wool_red_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(wool_black_slab), 0, new ModelResourceLocation(wool_black_slab.getRegistryName(), "inventory"));
			//STONE SLABS
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(mossy_cobblestone_slab), 0, new ModelResourceLocation(mossy_cobblestone_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(stone_andesite_slab), 0, new ModelResourceLocation(stone_andesite_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(stone_diorite_slab), 0, new ModelResourceLocation(stone_diorite_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(stone_granite_slab), 0, new ModelResourceLocation(stone_granite_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(stone_andesite_smooth_slab), 0, new ModelResourceLocation(stone_andesite_smooth_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(stone_diorite_smooth_slab), 0, new ModelResourceLocation(stone_diorite_smooth_slab.getRegistryName(), "inventory"));
			ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(stone_granite_smooth_slab), 0, new ModelResourceLocation(stone_granite_smooth_slab.getRegistryName(), "inventory"));
		}
		
		public static void registerBlockSlab(Block block, ItemBlock itemblock)
		{
			ForgeRegistries.BLOCKS.register(block);
			itemblock.setRegistryName(block.getRegistryName());
			ForgeRegistries.ITEMS.register(itemblock);
		}
	}
}
	
	



